<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $id = DB::table('states')
            ->insertGetId(['code' => '05', 'name' => strToupper('Antioquia'), 'country_id' => 47]);

        DB::table('cities')->insert([
            ['name' => 'MEDELLIN', 'code' => '001', 'state_id' => $id],
            ['name' => 'ABEJORRAL', 'code' => '002', 'state_id' => $id],
            ['name' => 'ABRIAQUI', 'code' => '004', 'state_id' => $id],
            ['name' => 'ALEJANDRIA', 'code' => '021', 'state_id' => $id],
            ['name' => 'AMAGA', 'code' => '030', 'state_id' => $id],
            ['name' => 'AMALFI', 'code' => '031', 'state_id' => $id],
            ['name' => 'ANDES', 'code' => '034', 'state_id' => $id],
            ['name' => 'ANGELOPOLIS', 'code' => '036', 'state_id' => $id],
            ['name' => 'ANGOSTURA', 'code' => '038', 'state_id' => $id],
            ['name' => 'ANORI', 'code' => '040', 'state_id' => $id],
            ['name' => 'SANTAFE DE ANTIOQUIA', 'code' => '042', 'state_id' => $id],
            ['name' => 'ANZA', 'code' => '044', 'state_id' => $id],
            ['name' => 'APARTADO', 'code' => '045', 'state_id' => $id],
            ['name' => 'ARBOLETES', 'code' => '051', 'state_id' => $id],
            ['name' => 'ARGELIA', 'code' => '055', 'state_id' => $id],
            ['name' => 'ARMENIA', 'code' => '059', 'state_id' => $id],
            ['name' => 'BARBOSA', 'code' => '079', 'state_id' => $id],
            ['name' => 'BELMIRA', 'code' => '086', 'state_id' => $id],
            ['name' => 'BELLO', 'code' => '088', 'state_id' => $id],
            ['name' => 'BETANIA', 'code' => '091', 'state_id' => $id],
            ['name' => 'BETULIA', 'code' => '093', 'state_id' => $id],
            ['name' => 'CIUDAD BOLIVAR', 'code' => '101', 'state_id' => $id],
            ['name' => 'BRICEÑO', 'code' => '107', 'state_id' => $id],
            ['name' => 'BURITICA', 'code' => '113', 'state_id' => $id],
            ['name' => 'CACERES', 'code' => '120', 'state_id' => $id],
            ['name' => 'CAICEDO', 'code' => '125', 'state_id' => $id],
            ['name' => 'CALDAS', 'code' => '129', 'state_id' => $id],
            ['name' => 'CAMPAMENTO', 'code' => '134', 'state_id' => $id],
            ['name' => 'CAÑASGORDAS', 'code' => '138', 'state_id' => $id],
            ['name' => 'CARACOLI', 'code' => '142', 'state_id' => $id],
            ['name' => 'CARAMANTA', 'code' => '145', 'state_id' => $id],
            ['name' => 'CAREPA', 'code' => '147', 'state_id' => $id],
            ['name' => 'EL CARMEN DE VIBORAL', 'code' => '148', 'state_id' => $id],
            ['name' => 'CAROLINA', 'code' => '150', 'state_id' => $id],
            ['name' => 'CAUCASIA', 'code' => '154', 'state_id' => $id],
            ['name' => 'CHIGORODO', 'code' => '172', 'state_id' => $id],
            ['name' => 'CISNEROS', 'code' => '190', 'state_id' => $id],
            ['name' => 'COCORNA', 'code' => '197', 'state_id' => $id],
            ['name' => 'CONCEPCION', 'code' => '206', 'state_id' => $id],
            ['name' => 'CONCORDIA', 'code' => '209', 'state_id' => $id],
            ['name' => 'COPACABANA', 'code' => '212', 'state_id' => $id],
            ['name' => 'DABEIBA', 'code' => '234', 'state_id' => $id],
            ['name' => 'DON MATIAS', 'code' => '237', 'state_id' => $id],
            ['name' => 'EBEJICO', 'code' => '240', 'state_id' => $id],
            ['name' => 'EL BAGRE', 'code' => '250', 'state_id' => $id],
            ['name' => 'ENTRERRIOS', 'code' => '264', 'state_id' => $id],
            ['name' => 'ENVIGADO', 'code' => '266', 'state_id' => $id],
            ['name' => 'FREDONIA', 'code' => '282', 'state_id' => $id],
            ['name' => 'FRONTINO', 'code' => '284', 'state_id' => $id],
            ['name' => 'GIRALDO', 'code' => '306', 'state_id' => $id],
            ['name' => 'GIRARDOTA', 'code' => '308', 'state_id' => $id],
            ['name' => 'GOMEZ PLATA', 'code' => '310', 'state_id' => $id],
            ['name' => 'GRANADA', 'code' => '313', 'state_id' => $id],
            ['name' => 'GUADALUPE', 'code' => '315', 'state_id' => $id],
            ['name' => 'GUARNE', 'code' => '318', 'state_id' => $id],
            ['name' => 'GUATAPE', 'code' => '321', 'state_id' => $id],
            ['name' => 'HELICONIA', 'code' => '347', 'state_id' => $id],
            ['name' => 'HISPANIA', 'code' => '353', 'state_id' => $id],
            ['name' => 'ITAGUI', 'code' => '360', 'state_id' => $id],
            ['name' => 'ITUANGO', 'code' => '361', 'state_id' => $id],
            ['name' => 'JARDIN', 'code' => '364', 'state_id' => $id],
            ['name' => 'JERICO', 'code' => '368', 'state_id' => $id],
            ['name' => 'LA CEJA', 'code' => '376', 'state_id' => $id],
            ['name' => 'LA ESTRELLA', 'code' => '380', 'state_id' => $id],
            ['name' => 'LA PINTADA', 'code' => '390', 'state_id' => $id],
            ['name' => 'LA UNION', 'code' => '400', 'state_id' => $id],
            ['name' => 'LIBORINA', 'code' => '411', 'state_id' => $id],
            ['name' => 'MACEO', 'code' => '425', 'state_id' => $id],
            ['name' => 'MARINILLA', 'code' => '440', 'state_id' => $id],
            ['name' => 'MONTEBELLO', 'code' => '467', 'state_id' => $id],
            ['name' => 'MURINDO', 'code' => '475', 'state_id' => $id],
            ['name' => 'MUTATA', 'code' => '480', 'state_id' => $id],
            ['name' => 'NARIÑO', 'code' => '483', 'state_id' => $id],
            ['name' => 'NECOCLI', 'code' => '490', 'state_id' => $id],
            ['name' => 'NECHI', 'code' => '495', 'state_id' => $id],
            ['name' => 'OLAYA', 'code' => '501', 'state_id' => $id],
            ['name' => 'PEÑOL', 'code' => '541', 'state_id' => $id],
            ['name' => 'PEQUE', 'code' => '543', 'state_id' => $id],
            ['name' => 'PUEBLORRICO', 'code' => '576', 'state_id' => $id],
            ['name' => 'PUERTO BERRIO', 'code' => '579', 'state_id' => $id],
            ['name' => 'PUERTO NARE', 'code' => '585', 'state_id' => $id],
            ['name' => 'PUERTO TRIUNFO', 'code' => '591', 'state_id' => $id],
            ['name' => 'REMEDIOS', 'code' => '604', 'state_id' => $id],
            ['name' => 'RETIRO', 'code' => '607', 'state_id' => $id],
            ['name' => 'RIONEGRO', 'code' => '615', 'state_id' => $id],
            ['name' => 'SABANALARGA', 'code' => '628', 'state_id' => $id],
            ['name' => 'SABANETA', 'code' => '631', 'state_id' => $id],
            ['name' => 'SALGAR', 'code' => '642', 'state_id' => $id],
            ['name' => 'SAN ANDRES', 'code' => '647', 'state_id' => $id],
            ['name' => 'SAN CARLOS', 'code' => '649', 'state_id' => $id],
            ['name' => 'SAN FRANCISCO', 'code' => '652', 'state_id' => $id],
            ['name' => 'SAN JERONIMO', 'code' => '656', 'state_id' => $id],
            ['name' => 'SAN JOSE DE LA MONTAÑA', 'code' => '658', 'state_id' => $id],
            ['name' => 'SAN JUAN DE URABA', 'code' => '659', 'state_id' => $id],
            ['name' => 'SAN LUIS', 'code' => '660', 'state_id' => $id],
            ['name' => 'SAN PEDRO', 'code' => '664', 'state_id' => $id],
            ['name' => 'SAN PEDRO DE URABA', 'code' => '665', 'state_id' => $id],
            ['name' => 'SAN RAFAEL', 'code' => '667', 'state_id' => $id],
            ['name' => 'SAN ROQUE', 'code' => '670', 'state_id' => $id],
            ['name' => 'SAN VICENTE', 'code' => '674', 'state_id' => $id],
            ['name' => 'SANTA BARBARA', 'code' => '679', 'state_id' => $id],
            ['name' => 'SANTA ROSA DE OSOS', 'code' => '686', 'state_id' => $id],
            ['name' => 'SANTO DOMINGO', 'code' => '690', 'state_id' => $id],
            ['name' => 'EL SANTUARIO', 'code' => '697', 'state_id' => $id],
            ['name' => 'SEGOVIA', 'code' => '736', 'state_id' => $id],
            ['name' => 'SONSON', 'code' => '756', 'state_id' => $id],
            ['name' => 'SOPETRAN', 'code' => '761', 'state_id' => $id],
            ['name' => 'TAMESIS', 'code' => '789', 'state_id' => $id],
            ['name' => 'TARAZA', 'code' => '790', 'state_id' => $id],
            ['name' => 'TARSO', 'code' => '792', 'state_id' => $id],
            ['name' => 'TITIRIBI', 'code' => '809', 'state_id' => $id],
            ['name' => 'TOLEDO', 'code' => '819', 'state_id' => $id],
            ['name' => 'TURBO', 'code' => '837', 'state_id' => $id],
            ['name' => 'URAMITA', 'code' => '842', 'state_id' => $id],
            ['name' => 'URRAO', 'code' => '847', 'state_id' => $id],
            ['name' => 'VALDIVIA', 'code' => '854', 'state_id' => $id],
            ['name' => 'VALPARAISO', 'code' => '856', 'state_id' => $id],
            ['name' => 'VEGACHI', 'code' => '858', 'state_id' => $id],
            ['name' => 'VENECIA', 'code' => '861', 'state_id' => $id],
            ['name' => 'VIGIA DEL FUERTE', 'code' => '873', 'state_id' => $id],
            ['name' => 'YALI', 'code' => '885', 'state_id' => $id],
            ['name' => 'YARUMAL', 'code' => '887', 'state_id' => $id],
            ['name' => 'YOLOMBO', 'code' => '890', 'state_id' => $id],
            ['name' => 'YONDO', 'code' => '893', 'state_id' => $id],
            ['name' => 'ZARAGOZA', 'code' => '895', 'state_id' => $id],
        ]);

        $id = DB::table('states')->insertGetId(
            ['code' => '08', 'name' => strToupper('AtlAntico'), 'country_id' => 47]
        );

        DB::table('cities')->insert([
            ['name' => 'BARRANQUILLA', 'code' => '001', 'state_id' => $id],
            ['name' => 'BARANOA', 'code' => '078', 'state_id' => $id],
            ['name' => 'CAMPO DE LA CRUZ', 'code' => '137', 'state_id' => $id],
            ['name' => 'CANDELARIA', 'code' => '141', 'state_id' => $id],
            ['name' => 'GALAPA', 'code' => '296', 'state_id' => $id],
            ['name' => 'JUAN DE ACOSTA', 'code' => '372', 'state_id' => $id],
            ['name' => 'LURUACO', 'code' => '421', 'state_id' => $id],
            ['name' => 'MALAMBO', 'code' => '433', 'state_id' => $id],
            ['name' => 'MANATI', 'code' => '436', 'state_id' => $id],
            ['name' => 'PALMAR DE VARELA', 'code' => '520', 'state_id' => $id],
            ['name' => 'PIOJO', 'code' => '549', 'state_id' => $id],
            ['name' => 'POLONUEVO', 'code' => '558', 'state_id' => $id],
            ['name' => 'PONEDERA', 'code' => '560', 'state_id' => $id],
            ['name' => 'PUERTO COLOMBIA', 'code' => '573', 'state_id' => $id],
            ['name' => 'REPELON', 'code' => '606', 'state_id' => $id],
            ['name' => 'SABANAGRANDE', 'code' => '634', 'state_id' => $id],
            ['name' => 'SABANALARGA', 'code' => '638', 'state_id' => $id],
            ['name' => 'SANTA LUCIA', 'code' => '675', 'state_id' => $id],
            ['name' => 'SANTO TOMAS', 'code' => '685', 'state_id' => $id],
            ['name' => 'SOLEDAD', 'code' => '758', 'state_id' => $id],
            ['name' => 'SUAN', 'code' => '770', 'state_id' => $id],
            ['name' => 'TUBARA', 'code' => '832', 'state_id' => $id],
            ['name' => 'USIACURI', 'code' => '849', 'state_id' => $id],
        ]);

        $id = DB::table('states')->insertGetId(
            ['code' => '11', 'name' => strToupper('BogotA D.C'), 'country_id' => 47]
        );

        DB::table('cities')->insert(['name' => 'BOGOTA', 'code' => '001', 'state_id' => $id]);

        $id = DB::table('states')->insertGetId(
            ['code' => '13', 'name' => strToupper('BolIvar'), 'country_id' => 47]
        );

        DB::table('cities')->insert([
            ['name' => 'CARTAGENA', 'code' => '001', 'state_id' => $id],
            ['name' => 'ACHI', 'code' => '006', 'state_id' => $id],
            ['name' => 'ALTOS DEL ROSARIO', 'code' => '030', 'state_id' => $id],
            ['name' => 'ARENAL', 'code' => '042', 'state_id' => $id],
            ['name' => 'ARJONA', 'code' => '052', 'state_id' => $id],
            ['name' => 'ARROYOHONDO', 'code' => '062', 'state_id' => $id],
            ['name' => 'BARRANCO DE LOBA', 'code' => '074', 'state_id' => $id],
            ['name' => 'CALAMAR', 'code' => '140', 'state_id' => $id],
            ['name' => 'CANTAGALLO', 'code' => '160', 'state_id' => $id],
            ['name' => 'CICUCO', 'code' => '188', 'state_id' => $id],
            ['name' => 'CORDOBA', 'code' => '212', 'state_id' => $id],
            ['name' => 'CLEMENCIA', 'code' => '222', 'state_id' => $id],
            ['name' => 'EL CARMEN DE BOLIVAR', 'code' => '244', 'state_id' => $id],
            ['name' => 'EL GUAMO', 'code' => '248', 'state_id' => $id],
            ['name' => 'EL PEÑON', 'code' => '268', 'state_id' => $id],
            ['name' => 'HATILLO DE LOBA', 'code' => '300', 'state_id' => $id],
            ['name' => 'MAGANGUE', 'code' => '430', 'state_id' => $id],
            ['name' => 'MAHATES', 'code' => '433', 'state_id' => $id],
            ['name' => 'MARGARITA', 'code' => '440', 'state_id' => $id],
            ['name' => 'MARIA LA BAJA', 'code' => '442', 'state_id' => $id],
            ['name' => 'MONTECRISTO', 'code' => '458', 'state_id' => $id],
            ['name' => 'MOMPOS', 'code' => '468', 'state_id' => $id],
            ['name' => 'MORALES', 'code' => '473', 'state_id' => $id],
            ['name' => 'PINILLOS', 'code' => '549', 'state_id' => $id],
            ['name' => 'REGIDOR', 'code' => '580', 'state_id' => $id],
            ['name' => 'RIO VIEJO', 'code' => '600', 'state_id' => $id],
            ['name' => 'SAN CRISTOBAL', 'code' => '620', 'state_id' => $id],
            ['name' => 'SAN ESTANISLAO', 'code' => '647', 'state_id' => $id],
            ['name' => 'SAN FERNANDO', 'code' => '650', 'state_id' => $id],
            ['name' => 'SAN JACINTO', 'code' => '654', 'state_id' => $id],
            ['name' => 'SAN JACINTO DEL CAUCA', 'code' => '655', 'state_id' => $id],
            ['name' => 'SAN JUAN NEPOMUCENO', 'code' => '657', 'state_id' => $id],
            ['name' => 'SAN MARTIN DE LOBA', 'code' => '667', 'state_id' => $id],
            ['name' => 'SAN PABLO', 'code' => '670', 'state_id' => $id],
            ['name' => 'SANTA CATALINA', 'code' => '673', 'state_id' => $id],
            ['name' => 'SANTA ROSA', 'code' => '683', 'state_id' => $id],
            ['name' => 'SANTA ROSA DEL SUR', 'code' => '688', 'state_id' => $id],
            ['name' => 'SIMITI', 'code' => '744', 'state_id' => $id],
            ['name' => 'SOPLAVIENTO', 'code' => '760', 'state_id' => $id],
            ['name' => 'TALAIGUA NUEVO', 'code' => '780', 'state_id' => $id],
            ['name' => 'TIQUISIO', 'code' => '810', 'state_id' => $id],
            ['name' => 'TURBACO', 'code' => '836', 'state_id' => $id],
            ['name' => 'TURBANA', 'code' => '838', 'state_id' => $id],
            ['name' => 'VILLANUEVA', 'code' => '873', 'state_id' => $id],
            ['name' => 'ZAMBRANO', 'code' => '894', 'state_id' => $id]            
        ]);

        $id = DB::table('states')->insertGetId(
            ['code' => '15', 'name' => strToupper('BoyacA'), 'country_id' => 47]
        );

        DB::table('cities')->insert([
            ['name' => 'TUNJA', 'code' => '001', 'state_id' => $id],
            ['name' => 'ALMEIDA', 'code' => '022', 'state_id' => $id],
            ['name' => 'AQUITANIA', 'code' => '047', 'state_id' => $id],
            ['name' => 'ARCABUCO', 'code' => '051', 'state_id' => $id],
            ['name' => 'BELEN', 'code' => '087', 'state_id' => $id],
            ['name' => 'BERBEO', 'code' => '090', 'state_id' => $id],
            ['name' => 'BETEITIVA', 'code' => '092', 'state_id' => $id],
            ['name' => 'BOAVITA', 'code' => '097', 'state_id' => $id],
            ['name' => 'BOYACA', 'code' => '104', 'state_id' => $id],
            ['name' => 'BRICEÑO', 'code' => '106', 'state_id' => $id],
            ['name' => 'BUENAVISTA', 'code' => '109', 'state_id' => $id],
            ['name' => 'BUSBANZA', 'code' => '114', 'state_id' => $id],
            ['name' => 'CALDAS', 'code' => '131', 'state_id' => $id],
            ['name' => 'CAMPOHERMOSO', 'code' => '135', 'state_id' => $id],
            ['name' => 'CERINZA', 'code' => '162', 'state_id' => $id],
            ['name' => 'CHINAVITA', 'code' => '172', 'state_id' => $id],
            ['name' => 'CHIQUINQUIRA', 'code' => '176', 'state_id' => $id],
            ['name' => 'CHISCAS', 'code' => '180', 'state_id' => $id],
            ['name' => 'CHITA', 'code' => '183', 'state_id' => $id],
            ['name' => 'CHITARAQUE', 'code' => '185', 'state_id' => $id],
            ['name' => 'CHIVATA', 'code' => '187', 'state_id' => $id],
            ['name' => 'CIENEGA', 'code' => '189', 'state_id' => $id],
            ['name' => 'COMBITA', 'code' => '204', 'state_id' => $id],
            ['name' => 'COPER', 'code' => '212', 'state_id' => $id],
            ['name' => 'CORRALES', 'code' => '215', 'state_id' => $id],
            ['name' => 'COVARACHIA', 'code' => '218', 'state_id' => $id],
            ['name' => 'CUBARA', 'code' => '223', 'state_id' => $id],
            ['name' => 'CUCAITA', 'code' => '224', 'state_id' => $id],
            ['name' => 'CUITIVA', 'code' => '226', 'state_id' => $id],
            ['name' => 'CHIQUIZA', 'code' => '232', 'state_id' => $id],
            ['name' => 'CHIVOR', 'code' => '236', 'state_id' => $id],
            ['name' => 'DUITAMA', 'code' => '238', 'state_id' => $id],
            ['name' => 'EL COCUY', 'code' => '244', 'state_id' => $id],
            ['name' => 'EL ESPINO', 'code' => '248', 'state_id' => $id],
            ['name' => 'FIRAVITOBA', 'code' => '272', 'state_id' => $id],
            ['name' => 'FLORESTA', 'code' => '276', 'state_id' => $id],
            ['name' => 'GACHANTIVA', 'code' => '293', 'state_id' => $id],
            ['name' => 'GAMEZA', 'code' => '296', 'state_id' => $id],
            ['name' => 'GARAGOA', 'code' => '299', 'state_id' => $id],
            ['name' => 'GUACAMAYAS', 'code' => '317', 'state_id' => $id],
            ['name' => 'GUATEQUE', 'code' => '322', 'state_id' => $id],
            ['name' => 'GUAYATA', 'code' => '325', 'state_id' => $id],
            ['name' => 'GÜICAN', 'code' => '332', 'state_id' => $id],
            ['name' => 'IZA', 'code' => '362', 'state_id' => $id],
            ['name' => 'JENESANO', 'code' => '367', 'state_id' => $id],
            ['name' => 'JERICO', 'code' => '368', 'state_id' => $id],
            ['name' => 'LABRANZAGRANDE', 'code' => '377', 'state_id' => $id],
            ['name' => 'LA CAPILLA', 'code' => '380', 'state_id' => $id],
            ['name' => 'LA VICTORIA', 'code' => '401', 'state_id' => $id],
            ['name' => 'LA UVITA', 'code' => '403', 'state_id' => $id],
            ['name' => 'VILLA DE LEYVA', 'code' => '407', 'state_id' => $id],
            ['name' => 'MACANAL', 'code' => '425', 'state_id' => $id],
            ['name' => 'MARIPI', 'code' => '442', 'state_id' => $id],
            ['name' => 'MIRAFLORES', 'code' => '455', 'state_id' => $id],
            ['name' => 'MONGUA', 'code' => '464', 'state_id' => $id],
            ['name' => 'MONGUI', 'code' => '466', 'state_id' => $id],
            ['name' => 'MONIQUIRA', 'code' => '469', 'state_id' => $id],
            ['name' => 'MOTAVITA', 'code' => '476', 'state_id' => $id],
            ['name' => 'MUZO', 'code' => '480', 'state_id' => $id],
            ['name' => 'NOBSA', 'code' => '491', 'state_id' => $id],
            ['name' => 'NUEVO COLON', 'code' => '494', 'state_id' => $id],
            ['name' => 'OICATA', 'code' => '500', 'state_id' => $id],
            ['name' => 'OTANCHE', 'code' => '507', 'state_id' => $id],
            ['name' => 'PACHAVITA', 'code' => '511', 'state_id' => $id],
            ['name' => 'PAEZ', 'code' => '514', 'state_id' => $id],
            ['name' => 'PAIPA', 'code' => '516', 'state_id' => $id],
            ['name' => 'PAJARITO', 'code' => '518', 'state_id' => $id],
            ['name' => 'PANQUEBA', 'code' => '522', 'state_id' => $id],
            ['name' => 'PAUNA', 'code' => '531', 'state_id' => $id],
            ['name' => 'PAYA', 'code' => '533', 'state_id' => $id],
            ['name' => 'PAZ DE RIO', 'code' => '537', 'state_id' => $id],
            ['name' => 'PESCA', 'code' => '542', 'state_id' => $id],
            ['name' => 'PISBA', 'code' => '550', 'state_id' => $id],
            ['name' => 'PUERTO BOYACA', 'code' => '572', 'state_id' => $id],
            ['name' => 'QUIPAMA', 'code' => '580', 'state_id' => $id],
            ['name' => 'RAMIRIQUI', 'code' => '599', 'state_id' => $id],
            ['name' => 'RAQUIRA', 'code' => '600', 'state_id' => $id],
            ['name' => 'RONDON', 'code' => '621', 'state_id' => $id],
            ['name' => 'SABOYA', 'code' => '632', 'state_id' => $id],
            ['name' => 'SACHICA', 'code' => '638', 'state_id' => $id],
            ['name' => 'SAMACA', 'code' => '646', 'state_id' => $id],
            ['name' => 'SAN EDUARDO', 'code' => '660', 'state_id' => $id],
            ['name' => 'SAN JOSE DE PARE', 'code' => '664', 'state_id' => $id],
            ['name' => 'SAN LUIS DE GACENO', 'code' => '667', 'state_id' => $id],
            ['name' => 'SAN MATEO', 'code' => '673', 'state_id' => $id],
            ['name' => 'SAN MIGUEL DE SEMA', 'code' => '676', 'state_id' => $id],
            ['name' => 'SAN PABLO DE BORBUR', 'code' => '681', 'state_id' => $id],
            ['name' => 'SANTANA', 'code' => '686', 'state_id' => $id],
            ['name' => 'SANTA MARIA', 'code' => '690', 'state_id' => $id],
            ['name' => 'SANTA ROSA DE VITERBO', 'code' => '693', 'state_id' => $id],
            ['name' => 'SANTA SOFIA', 'code' => '696', 'state_id' => $id],
            ['name' => 'SATIVANORTE', 'code' => '720', 'state_id' => $id],
            ['name' => 'SATIVASUR', 'code' => '723', 'state_id' => $id],
            ['name' => 'SIACHOQUE', 'code' => '740', 'state_id' => $id],
            ['name' => 'SOATA', 'code' => '753', 'state_id' => $id],
            ['name' => 'SOCOTA', 'code' => '755', 'state_id' => $id],
            ['name' => 'SOCHA', 'code' => '757', 'state_id' => $id],
            ['name' => 'SOGAMOSO', 'code' => '759', 'state_id' => $id],
            ['name' => 'SOMONDOCO', 'code' => '761', 'state_id' => $id],
            ['name' => 'SORA', 'code' => '762', 'state_id' => $id],
            ['name' => 'SOTAQUIRA', 'code' => '763', 'state_id' => $id],
            ['name' => 'SORACA', 'code' => '764', 'state_id' => $id],
            ['name' => 'SUSACON', 'code' => '774', 'state_id' => $id],
            ['name' => 'SUTAMARCHAN', 'code' => '776', 'state_id' => $id],
            ['name' => 'SUTATENZA', 'code' => '778', 'state_id' => $id],
            ['name' => 'TASCO', 'code' => '790', 'state_id' => $id],
            ['name' => 'TENZA', 'code' => '798', 'state_id' => $id],
            ['name' => 'TIBANA', 'code' => '804', 'state_id' => $id],
            ['name' => 'TIBASOSA', 'code' => '806', 'state_id' => $id],
            ['name' => 'TINJACA', 'code' => '808', 'state_id' => $id],
            ['name' => 'TIPACOQUE', 'code' => '810', 'state_id' => $id],
            ['name' => 'TOCA', 'code' => '814', 'state_id' => $id],
            ['name' => 'TOGÜI', 'code' => '816', 'state_id' => $id],
            ['name' => 'TOPAGA', 'code' => '820', 'state_id' => $id],
            ['name' => 'TOTA', 'code' => '822', 'state_id' => $id],
            ['name' => 'TUNUNGUA', 'code' => '832', 'state_id' => $id],
            ['name' => 'TURMEQUE', 'code' => '835', 'state_id' => $id],
            ['name' => 'TUTA', 'code' => '837', 'state_id' => $id],
            ['name' => 'TUTAZA', 'code' => '839', 'state_id' => $id],
            ['name' => 'UMBITA', 'code' => '842', 'state_id' => $id],
            ['name' => 'VENTAQUEMADA', 'code' => '861', 'state_id' => $id],
            ['name' => 'VIRACACHA', 'code' => '879', 'state_id' => $id],
            ['name' => 'ZETAQUIRA', 'code' => '897', 'state_id' => $id],
        ]);

        $id = DB::table('states')->insertGetId(
            ['code' => '17', 'name' => strToupper('Caldas'), 'country_id' => 47]
        );

        DB::table('cities')->insert([
            ['name' => 'MANIZALES', 'code' => '001', 'state_id' => $id],
            ['name' => 'AGUADAS', 'code' => '013', 'state_id' => $id],
            ['name' => 'ANSERMA', 'code' => '042', 'state_id' => $id],
            ['name' => 'ARANZAZU', 'code' => '050', 'state_id' => $id],
            ['name' => 'BELALCAZAR', 'code' => '088', 'state_id' => $id],
            ['name' => 'CHINCHINA', 'code' => '174', 'state_id' => $id],
            ['name' => 'FILADELFIA', 'code' => '272', 'state_id' => $id],
            ['name' => 'LA DORADA', 'code' => '380', 'state_id' => $id],
            ['name' => 'LA MERCED', 'code' => '388', 'state_id' => $id],
            ['name' => 'MANZANARES', 'code' => '433', 'state_id' => $id],
            ['name' => 'MARMATO', 'code' => '442', 'state_id' => $id],
            ['name' => 'MARQUETALIA', 'code' => '444', 'state_id' => $id],
            ['name' => 'MARULANDA', 'code' => '446', 'state_id' => $id],
            ['name' => 'NEIRA', 'code' => '486', 'state_id' => $id],
            ['name' => 'NORCASIA', 'code' => '495', 'state_id' => $id],
            ['name' => 'PACORA', 'code' => '513', 'state_id' => $id],
            ['name' => 'PALESTINA', 'code' => '524', 'state_id' => $id],
            ['name' => 'PENSILVANIA', 'code' => '541', 'state_id' => $id],
            ['name' => 'RIOSUCIO', 'code' => '614', 'state_id' => $id],
            ['name' => 'RISARALDA', 'code' => '616', 'state_id' => $id],
            ['name' => 'SALAMINA', 'code' => '653', 'state_id' => $id],
            ['name' => 'SAMANA', 'code' => '662', 'state_id' => $id],
            ['name' => 'SAN JOSE', 'code' => '665', 'state_id' => $id],
            ['name' => 'SUPIA', 'code' => '777', 'state_id' => $id],
            ['name' => 'VICTORIA', 'code' => '867', 'state_id' => $id],
            ['name' => 'VILLAMARIA', 'code' => '873', 'state_id' => $id],
            ['name' => 'VITERBO', 'code' => '877', 'state_id' => $id]
        ]);

        $id = DB::table('states')->insertGetId(
            ['code' => '18', 'name' => strToupper('CaquetA'), 'country_id' => 47]
        );

        DB::table('cities')->insert([
            ['name' => 'FLORENCIA', 'code' => '001', 'state_id' => $id],
            ['name' => 'ALBANIA', 'code' => '029', 'state_id' => $id],
            ['name' => 'BELEN DE LOS ANDAQUIES', 'code' => '094', 'state_id' => $id],
            ['name' => 'CARTAGENA DEL CHAIRA', 'code' => '150', 'state_id' => $id],
            ['name' => 'CURILLO', 'code' => '205', 'state_id' => $id],
            ['name' => 'EL DONCELLO', 'code' => '247', 'state_id' => $id],
            ['name' => 'EL PAUJIL', 'code' => '256', 'state_id' => $id],
            ['name' => 'LA MONTAÑITA', 'code' => '410', 'state_id' => $id],
            ['name' => 'MILAN', 'code' => '460', 'state_id' => $id],
            ['name' => 'MORELIA', 'code' => '479', 'state_id' => $id],
            ['name' => 'PUERTO RICO', 'code' => '592', 'state_id' => $id],
            ['name' => 'SAN JOSE DEL FRAGUA', 'code' => '610', 'state_id' => $id],
            ['name' => 'SAN VICENTE DEL CAGUAN', 'code' => '753', 'state_id' => $id],
            ['name' => 'SOLANO', 'code' => '756', 'state_id' => $id],
            ['name' => 'SOLITA', 'code' => '785', 'state_id' => $id],
            ['name' => 'VALPARAISO', 'code' => '860', 'state_id' => $id],
        ]);

        $id = DB::table('states')->insertGetId(
            ['code' => '19', 'name' => strToupper('Cauca'), 'country_id' => 47]
        );

        DB::table('cities')->insert([
            ['name' => 'POPAYAN', 'code' => '001', 'state_id' => $id],
            ['name' => 'ALMAGUER', 'code' => '022', 'state_id' => $id],
            ['name' => 'ARGELIA', 'code' => '050', 'state_id' => $id],
            ['name' => 'BALBOA', 'code' => '075', 'state_id' => $id],
            ['name' => 'BOLIVAR', 'code' => '100', 'state_id' => $id],
            ['name' => 'BUENOS AIRES', 'code' => '110', 'state_id' => $id],
            ['name' => 'CAJIBIO', 'code' => '130', 'state_id' => $id],
            ['name' => 'CALDONO', 'code' => '137', 'state_id' => $id],
            ['name' => 'CALOTO', 'code' => '142', 'state_id' => $id],
            ['name' => 'CORINTO', 'code' => '212', 'state_id' => $id],
            ['name' => 'EL TAMBO', 'code' => '256', 'state_id' => $id],
            ['name' => 'FLORENCIA', 'code' => '290', 'state_id' => $id],
            ['name' => 'GUAPI', 'code' => '318', 'state_id' => $id],
            ['name' => 'INZA', 'code' => '355', 'state_id' => $id],
            ['name' => 'JAMBALO', 'code' => '364', 'state_id' => $id],
            ['name' => 'LA SIERRA', 'code' => '392', 'state_id' => $id],
            ['name' => 'LA VEGA', 'code' => '397', 'state_id' => $id],
            ['name' => 'LOPEZ', 'code' => '418', 'state_id' => $id],
            ['name' => 'MERCADERES', 'code' => '450', 'state_id' => $id],
            ['name' => 'MIRANDA', 'code' => '455', 'state_id' => $id],
            ['name' => 'MORALES', 'code' => '473', 'state_id' => $id],
            ['name' => 'PADILLA', 'code' => '513', 'state_id' => $id],
            ['name' => 'PAEZ', 'code' => '517', 'state_id' => $id],
            ['name' => 'PATIA', 'code' => '532', 'state_id' => $id],
            ['name' => 'PIAMONTE', 'code' => '533', 'state_id' => $id],
            ['name' => 'PIENDAMO', 'code' => '548', 'state_id' => $id],
            ['name' => 'PUERTO TEJADA', 'code' => '573', 'state_id' => $id],
            ['name' => 'PURACE', 'code' => '585', 'state_id' => $id],
            ['name' => 'ROSAS', 'code' => '622', 'state_id' => $id],
            ['name' => 'SAN SEBASTIAN', 'code' => '693', 'state_id' => $id],
            ['name' => 'SANTANDER DE QUILICHAO', 'code' => '698', 'state_id' => $id],
            ['name' => 'SANTA ROSA', 'code' => '701', 'state_id' => $id],
            ['name' => 'SILVIA', 'code' => '743', 'state_id' => $id],
            ['name' => 'SOTARA', 'code' => '760', 'state_id' => $id],
            ['name' => 'SUAREZ', 'code' => '780', 'state_id' => $id],
            ['name' => 'SUCRE', 'code' => '785', 'state_id' => $id],
            ['name' => 'TIMBIO', 'code' => '807', 'state_id' => $id],
            ['name' => 'TIMBIQUI', 'code' => '809', 'state_id' => $id],
            ['name' => 'TORIBIO', 'code' => '821', 'state_id' => $id],
            ['name' => 'TOTORO', 'code' => '824', 'state_id' => $id],
            ['name' => 'VILLA RICA', 'code' => '845', 'state_id' => $id],
        ]);

        $id = DB::table('states')->insertGetId(
            ['code' => '20', 'name' => strToupper('Cesar'), 'country_id' => 47]
        );

        DB::table('cities')->insert([
            ['name' => 'VALLEDUPAR', 'code' => '001', 'state_id' => $id],
            ['name' => 'AGUACHICA', 'code' => '011', 'state_id' => $id],
            ['name' => 'AGUSTIN CODAZZI', 'code' => '013', 'state_id' => $id],
            ['name' => 'ASTREA', 'code' => '032', 'state_id' => $id],
            ['name' => 'BECERRIL', 'code' => '045', 'state_id' => $id],
            ['name' => 'BOSCONIA', 'code' => '060', 'state_id' => $id],
            ['name' => 'CHIMICHAGUA', 'code' => '175', 'state_id' => $id],
            ['name' => 'CHIRIGUANA', 'code' => '178', 'state_id' => $id],
            ['name' => 'CURUMANI', 'code' => '228', 'state_id' => $id],
            ['name' => 'EL COPEY', 'code' => '238', 'state_id' => $id],
            ['name' => 'EL PASO', 'code' => '250', 'state_id' => $id],
            ['name' => 'GAMARRA', 'code' => '295', 'state_id' => $id],
            ['name' => 'GONZALEZ', 'code' => '310', 'state_id' => $id],
            ['name' => 'LA GLORIA', 'code' => '383', 'state_id' => $id],
            ['name' => 'LA JAGUA DE IBIRICO', 'code' => '400', 'state_id' => $id],
            ['name' => 'MANAURE', 'code' => '443', 'state_id' => $id],
            ['name' => 'PAILITAS', 'code' => '517', 'state_id' => $id],
            ['name' => 'PELAYA', 'code' => '550', 'state_id' => $id],
            ['name' => 'PUEBLO BELLO', 'code' => '570', 'state_id' => $id],
            ['name' => 'RIO DE ORO', 'code' => '614', 'state_id' => $id],
            ['name' => 'LA PAZ', 'code' => '621', 'state_id' => $id],
            ['name' => 'SAN ALBERTO', 'code' => '710', 'state_id' => $id],
            ['name' => 'SAN DIEGO', 'code' => '750', 'state_id' => $id],
            ['name' => 'SAN MARTIN', 'code' => '770', 'state_id' => $id],
            ['name' => 'TAMALAMEQUE', 'code' => '787', 'state_id' => $id],
        ]);

        $id = DB::table('states')->insertGetId(
            ['code' => '23', 'name' => strToupper('COrdoba'), 'country_id' => 47]
        );

        DB::table('cities')->insert([
            ['name' => 'MONTERIA', 'code' => '001', 'state_id' => $id],
            ['name' => 'AYAPEL', 'code' => '068', 'state_id' => $id],
            ['name' => 'BUENAVISTA', 'code' => '079', 'state_id' => $id],
            ['name' => 'CANALETE', 'code' => '090', 'state_id' => $id],
            ['name' => 'CERETE', 'code' => '162', 'state_id' => $id],
            ['name' => 'CHIMA', 'code' => '168', 'state_id' => $id],
            ['name' => 'CHINU', 'code' => '182', 'state_id' => $id],
            ['name' => 'CIENAGA DE ORO', 'code' => '189', 'state_id' => $id],
            ['name' => 'COTORRA', 'code' => '300', 'state_id' => $id],
            ['name' => 'LA APARTADA', 'code' => '350', 'state_id' => $id],
            ['name' => 'LORICA', 'code' => '417', 'state_id' => $id],
            ['name' => 'LOS CORDOBAS', 'code' => '419', 'state_id' => $id],
            ['name' => 'MOMIL', 'code' => '464', 'state_id' => $id],
            ['name' => 'MONTELIBANO', 'code' => '466', 'state_id' => $id],
            ['name' => 'MOÑITOS', 'code' => '500', 'state_id' => $id],
            ['name' => 'PLANETA RICA', 'code' => '555', 'state_id' => $id],
            ['name' => 'PUEBLO NUEVO', 'code' => '570', 'state_id' => $id],
            ['name' => 'PUERTO ESCONDIDO', 'code' => '574', 'state_id' => $id],
            ['name' => 'PUERTO LIBERTADOR', 'code' => '580', 'state_id' => $id],
            ['name' => 'PURISIMA', 'code' => '586', 'state_id' => $id],
            ['name' => 'SAHAGUN', 'code' => '660', 'state_id' => $id],
            ['name' => 'SAN ANDRES SOTAVENTO', 'code' => '670', 'state_id' => $id],
            ['name' => 'SAN ANTERO', 'code' => '672', 'state_id' => $id],
            ['name' => 'SAN BERNARDO DEL VIENTO', 'code' => '675', 'state_id' => $id],
            ['name' => 'SAN CARLOS', 'code' => '678', 'state_id' => $id],
            ['name' => 'SAN PELAYO', 'code' => '686', 'state_id' => $id],
            ['name' => 'TIERRALTA', 'code' => '807', 'state_id' => $id],
            ['name' => 'VALENCIA', 'code' => '855', 'state_id' => $id],
        ]);

        $id = DB::table('states')->insertGetId(
            ['code' => '25', 'name' => strToupper('Cundinamarca'), 'country_id' => 47]
        );

        DB::table('cities')->insert([
            ['name' => 'AGUA DE DIOS', 'code' => '001', 'state_id' => $id],
            ['name' => 'ALBAN', 'code' => '019', 'state_id' => $id],
            ['name' => 'ANAPOIMA', 'code' => '035', 'state_id' => $id],
            ['name' => 'ANOLAIMA', 'code' => '040', 'state_id' => $id],
            ['name' => 'ARBELAEZ', 'code' => '053', 'state_id' => $id],
            ['name' => 'BELTRAN', 'code' => '086', 'state_id' => $id],
            ['name' => 'BITUIMA', 'code' => '095', 'state_id' => $id],
            ['name' => 'BOJACA', 'code' => '099', 'state_id' => $id],
            ['name' => 'CABRERA', 'code' => '120', 'state_id' => $id],
            ['name' => 'CACHIPAY', 'code' => '123', 'state_id' => $id],
            ['name' => 'CAJICA', 'code' => '126', 'state_id' => $id],
            ['name' => 'CAPARRAPI', 'code' => '148', 'state_id' => $id],
            ['name' => 'CAQUEZA', 'code' => '151', 'state_id' => $id],
            ['name' => 'CARMEN DE CARUPA', 'code' => '154', 'state_id' => $id],
            ['name' => 'CHAGUANI', 'code' => '168', 'state_id' => $id],
            ['name' => 'CHIA', 'code' => '175', 'state_id' => $id],
            ['name' => 'CHIPAQUE', 'code' => '178', 'state_id' => $id],
            ['name' => 'CHOACHI', 'code' => '181', 'state_id' => $id],
            ['name' => 'CHOCONTA', 'code' => '183', 'state_id' => $id],
            ['name' => 'COGUA', 'code' => '200', 'state_id' => $id],
            ['name' => 'COTA', 'code' => '214', 'state_id' => $id],
            ['name' => 'CUCUNUBA', 'code' => '224', 'state_id' => $id],
            ['name' => 'EL COLEGIO', 'code' => '245', 'state_id' => $id],
            ['name' => 'EL PEÑON', 'code' => '258', 'state_id' => $id],
            ['name' => 'EL ROSAL', 'code' => '260', 'state_id' => $id],
            ['name' => 'FACATATIVA', 'code' => '269', 'state_id' => $id],
            ['name' => 'FOMEQUE', 'code' => '279', 'state_id' => $id],
            ['name' => 'FOSCA', 'code' => '281', 'state_id' => $id],
            ['name' => 'FUNZA', 'code' => '286', 'state_id' => $id],
            ['name' => 'FUQUENE', 'code' => '288', 'state_id' => $id],
            ['name' => 'FUSAGASUGA', 'code' => '290', 'state_id' => $id],
            ['name' => 'GACHALA', 'code' => '293', 'state_id' => $id],
            ['name' => 'GACHANCIPA', 'code' => '295', 'state_id' => $id],
            ['name' => 'GACHETA', 'code' => '297', 'state_id' => $id],
            ['name' => 'GAMA', 'code' => '299', 'state_id' => $id],
            ['name' => 'GIRARDOT', 'code' => '307', 'state_id' => $id],
            ['name' => 'GRANADA', 'code' => '312', 'state_id' => $id],
            ['name' => 'GUACHETA', 'code' => '317', 'state_id' => $id],
            ['name' => 'GUADUAS', 'code' => '320', 'state_id' => $id],
            ['name' => 'GUASCA', 'code' => '322', 'state_id' => $id],
            ['name' => 'GUATAQUI', 'code' => '324', 'state_id' => $id],
            ['name' => 'GUATAVITA', 'code' => '326', 'state_id' => $id],
            ['name' => 'GUAYABAL DE SIQUIMA', 'code' => '328', 'state_id' => $id],
            ['name' => 'GUAYABETAL', 'code' => '335', 'state_id' => $id],
            ['name' => 'GUTIERREZ', 'code' => '339', 'state_id' => $id],
            ['name' => 'JERUSALEN', 'code' => '368', 'state_id' => $id],
            ['name' => 'JUNIN', 'code' => '372', 'state_id' => $id],
            ['name' => 'LA CALERA', 'code' => '377', 'state_id' => $id],
            ['name' => 'LA MESA', 'code' => '386', 'state_id' => $id],
            ['name' => 'LA PALMA', 'code' => '394', 'state_id' => $id],
            ['name' => 'LA PEÑA', 'code' => '398', 'state_id' => $id],
            ['name' => 'LA VEGA', 'code' => '402', 'state_id' => $id],
            ['name' => 'LENGUAZAQUE', 'code' => '407', 'state_id' => $id],
            ['name' => 'MACHETA', 'code' => '426', 'state_id' => $id],
            ['name' => 'MADRID', 'code' => '430', 'state_id' => $id],
            ['name' => 'MANTA', 'code' => '436', 'state_id' => $id],
            ['name' => 'MEDINA', 'code' => '438', 'state_id' => $id],
            ['name' => 'MOSQUERA', 'code' => '473', 'state_id' => $id],
            ['name' => 'NARIÑO', 'code' => '483', 'state_id' => $id],
            ['name' => 'NEMOCON', 'code' => '486', 'state_id' => $id],
            ['name' => 'NILO', 'code' => '488', 'state_id' => $id],
            ['name' => 'NIMAIMA', 'code' => '489', 'state_id' => $id],
            ['name' => 'NOCAIMA', 'code' => '491', 'state_id' => $id],
            ['name' => 'VENECIA', 'code' => '506', 'state_id' => $id],
            ['name' => 'PACHO', 'code' => '513', 'state_id' => $id],
            ['name' => 'PAIME', 'code' => '518', 'state_id' => $id],
            ['name' => 'PANDI', 'code' => '524', 'state_id' => $id],
            ['name' => 'PARATEBUENO', 'code' => '530', 'state_id' => $id],
            ['name' => 'PASCA', 'code' => '535', 'state_id' => $id],
            ['name' => 'PUERTO SALGAR', 'code' => '572', 'state_id' => $id],
            ['name' => 'PULI', 'code' => '580', 'state_id' => $id],
            ['name' => 'QUEBRADANEGRA', 'code' => '592', 'state_id' => $id],
            ['name' => 'QUETAME', 'code' => '594', 'state_id' => $id],
            ['name' => 'QUIPILE', 'code' => '596', 'state_id' => $id],
            ['name' => 'APULO', 'code' => '599', 'state_id' => $id],
            ['name' => 'RICAURTE', 'code' => '612', 'state_id' => $id],
            ['name' => 'SAN ANTONIO DEL TEQUENDAMA', 'code' => '645', 'state_id' => $id],
            ['name' => 'SAN BERNARDO', 'code' => '649', 'state_id' => $id],
            ['name' => 'SAN CAYETANO', 'code' => '653', 'state_id' => $id],
            ['name' => 'SAN FRANCISCO', 'code' => '658', 'state_id' => $id],
            ['name' => 'SAN JUAN DE RIO SECO', 'code' => '662', 'state_id' => $id],
            ['name' => 'SASAIMA', 'code' => '718', 'state_id' => $id],
            ['name' => 'SESQUILE', 'code' => '736', 'state_id' => $id],
            ['name' => 'SIBATE', 'code' => '740', 'state_id' => $id],
            ['name' => 'SILVANIA', 'code' => '743', 'state_id' => $id],
            ['name' => 'SIMIJACA', 'code' => '745', 'state_id' => $id],
            ['name' => 'SOACHA', 'code' => '754', 'state_id' => $id],
            ['name' => 'SOPO', 'code' => '758', 'state_id' => $id],
            ['name' => 'SUBACHOQUE', 'code' => '769', 'state_id' => $id],
            ['name' => 'SUESCA', 'code' => '772', 'state_id' => $id],
            ['name' => 'SUPATA', 'code' => '777', 'state_id' => $id],
            ['name' => 'SUSA', 'code' => '779', 'state_id' => $id],
            ['name' => 'SUTATAUSA', 'code' => '781', 'state_id' => $id],
            ['name' => 'TABIO', 'code' => '785', 'state_id' => $id],
            ['name' => 'TAUSA', 'code' => '793', 'state_id' => $id],
            ['name' => 'TENA', 'code' => '797', 'state_id' => $id],
            ['name' => 'TENJO', 'code' => '799', 'state_id' => $id],
            ['name' => 'TIBACUY', 'code' => '805', 'state_id' => $id],
            ['name' => 'TIBIRITA', 'code' => '807', 'state_id' => $id],
            ['name' => 'TOCAIMA', 'code' => '815', 'state_id' => $id],
            ['name' => 'TOCANCIPA', 'code' => '817', 'state_id' => $id],
            ['name' => 'TOPAIPI', 'code' => '823', 'state_id' => $id],
            ['name' => 'UBALA', 'code' => '839', 'state_id' => $id],
            ['name' => 'UBAQUE', 'code' => '841', 'state_id' => $id],
            ['name' => 'VILLA DE SAN DIEGO DE UBATE', 'code' => '843', 'state_id' => $id],
            ['name' => 'UNE', 'code' => '845', 'state_id' => $id],
            ['name' => 'UTICA', 'code' => '851', 'state_id' => $id],
            ['name' => 'VERGARA', 'code' => '862', 'state_id' => $id],
            ['name' => 'VIANI', 'code' => '867', 'state_id' => $id],
            ['name' => 'VILLAGOMEZ', 'code' => '871', 'state_id' => $id],
            ['name' => 'VILLAPINZON', 'code' => '873', 'state_id' => $id],
            ['name' => 'VILLETA', 'code' => '875', 'state_id' => $id],
            ['name' => 'VIOTA', 'code' => '878', 'state_id' => $id],
            ['name' => 'YACOPI', 'code' => '885', 'state_id' => $id],
            ['name' => 'ZIPACON', 'code' => '898', 'state_id' => $id],
            ['name' => 'ZIPAQUIRA', 'code' => '899', 'state_id' => $id],
        ]);

        $id = DB::table('states')->insertGetId(
            ['code' => '27', 'name' => strToupper('ChocO'), 'country_id' => 47]
        );

        DB::table('cities')->insert([
            ['name' => 'QUIBDO', 'code' => '001', 'state_id' => $id],
            ['name' => 'ACANDI', 'code' => '006', 'state_id' => $id],
            ['name' => 'ALTO BAUDO', 'code' => '025', 'state_id' => $id],
            ['name' => 'ATRATO', 'code' => '050', 'state_id' => $id],
            ['name' => 'BAGADO', 'code' => '073', 'state_id' => $id],
            ['name' => 'BAHIA SOLANO', 'code' => '075', 'state_id' => $id],
            ['name' => 'BAJO BAUDO', 'code' => '077', 'state_id' => $id],
            ['name' => 'BELEN DE BAJIRA', 'code' => '086', 'state_id' => $id],
            ['name' => 'BOJAYA', 'code' => '099', 'state_id' => $id],
            ['name' => 'EL CANTON DEL SAN PABLO', 'code' => '135', 'state_id' => $id],
            ['name' => 'CARMEN DEL DARIEN', 'code' => '150', 'state_id' => $id],
            ['name' => 'CERTEGUI', 'code' => '160', 'state_id' => $id],
            ['name' => 'CONDOTO', 'code' => '205', 'state_id' => $id],
            ['name' => 'EL CARMEN DE ATRATO', 'code' => '245', 'state_id' => $id],
            ['name' => 'EL LITORAL DEL SAN JUAN', 'code' => '250', 'state_id' => $id],
            ['name' => 'ISTMINA', 'code' => '361', 'state_id' => $id],
            ['name' => 'JURADO', 'code' => '372', 'state_id' => $id],
            ['name' => 'LLORO', 'code' => '413', 'state_id' => $id],
            ['name' => 'MEDIO ATRATO', 'code' => '425', 'state_id' => $id],
            ['name' => 'MEDIO BAUDO', 'code' => '430', 'state_id' => $id],
            ['name' => 'MEDIO SAN JUAN', 'code' => '450', 'state_id' => $id],
            ['name' => 'NOVITA', 'code' => '491', 'state_id' => $id],
            ['name' => 'NUQUI', 'code' => '495', 'state_id' => $id],
            ['name' => 'RIO IRO', 'code' => '580', 'state_id' => $id],
            ['name' => 'RIO QUITO', 'code' => '600', 'state_id' => $id],
            ['name' => 'RIOSUCIO', 'code' => '615', 'state_id' => $id],
            ['name' => 'SAN JOSE DEL PALMAR', 'code' => '660', 'state_id' => $id],
            ['name' => 'SIPI', 'code' => '745', 'state_id' => $id],
            ['name' => 'TADO', 'code' => '787', 'state_id' => $id],
            ['name' => 'UNGUIA', 'code' => '800', 'state_id' => $id],
            ['name' => 'UNION PANAMERICANA', 'code' => '810', 'state_id' => $id],
        ]);

        $id = DB::table('states')->insertGetId(
            ['code' => '41', 'name' => strToupper('Huila'), 'country_id' => 47]
        );

        DB::table('cities')->insert([
            ['name' => 'NEIVA', 'code' => '001', 'state_id' => $id],
            ['name' => 'ACEVEDO', 'code' => '006', 'state_id' => $id],
            ['name' => 'AGRADO', 'code' => '013', 'state_id' => $id],
            ['name' => 'AIPE', 'code' => '016', 'state_id' => $id],
            ['name' => 'ALGECIRAS', 'code' => '020', 'state_id' => $id],
            ['name' => 'ALTAMIRA', 'code' => '026', 'state_id' => $id],
            ['name' => 'BARAYA', 'code' => '078', 'state_id' => $id],
            ['name' => 'CAMPOALEGRE', 'code' => '132', 'state_id' => $id],
            ['name' => 'COLOMBIA', 'code' => '206', 'state_id' => $id],
            ['name' => 'ELIAS', 'code' => '244', 'state_id' => $id],
            ['name' => 'GARZON', 'code' => '298', 'state_id' => $id],
            ['name' => 'GIGANTE', 'code' => '306', 'state_id' => $id],
            ['name' => 'GUADALUPE', 'code' => '319', 'state_id' => $id],
            ['name' => 'HOBO', 'code' => '349', 'state_id' => $id],
            ['name' => 'IQUIRA', 'code' => '357', 'state_id' => $id],
            ['name' => 'ISNOS', 'code' => '359', 'state_id' => $id],
            ['name' => 'LA ARGENTINA', 'code' => '378', 'state_id' => $id],
            ['name' => 'LA PLATA', 'code' => '396', 'state_id' => $id],
            ['name' => 'NATAGA', 'code' => '483', 'state_id' => $id],
            ['name' => 'OPORAPA', 'code' => '503', 'state_id' => $id],
            ['name' => 'PAICOL', 'code' => '518', 'state_id' => $id],
            ['name' => 'PALERMO', 'code' => '524', 'state_id' => $id],
            ['name' => 'PALESTINA', 'code' => '530', 'state_id' => $id],
            ['name' => 'PITAL', 'code' => '548', 'state_id' => $id],
            ['name' => 'PITALITO', 'code' => '551', 'state_id' => $id],
            ['name' => 'RIVERA', 'code' => '615', 'state_id' => $id],
            ['name' => 'SALADOBLANCO', 'code' => '660', 'state_id' => $id],
            ['name' => 'SAN AGUSTIN', 'code' => '668', 'state_id' => $id],
            ['name' => 'SANTA MARIA', 'code' => '676', 'state_id' => $id],
            ['name' => 'SUAZA', 'code' => '770', 'state_id' => $id],
            ['name' => 'TARQUI', 'code' => '791', 'state_id' => $id],
            ['name' => 'TESALIA', 'code' => '797', 'state_id' => $id],
            ['name' => 'TELLO', 'code' => '799', 'state_id' => $id],
            ['name' => 'TERUEL', 'code' => '801', 'state_id' => $id],
            ['name' => 'TIMANA', 'code' => '807', 'state_id' => $id],
            ['name' => 'VILLAVIEJA', 'code' => '872', 'state_id' => $id],
            ['name' => 'YAGUARA', 'code' => '885', 'state_id' => $id],
        ]);

        $id = DB::table('states')->insertGetId(
            ['code' => '44', 'name' => strToupper('La Guajira'), 'country_id' => 47]
        );

        DB::table('cities')->insert([
            ['name' => 'RIOHACHA', 'code' => '001', 'state_id' => $id],
            ['name' => 'ALBANIA', 'code' => '035', 'state_id' => $id],
            ['name' => 'BARRANCAS', 'code' => '078', 'state_id' => $id],
            ['name' => 'DIBULLA', 'code' => '090', 'state_id' => $id],
            ['name' => 'DISTRACCION', 'code' => '098', 'state_id' => $id],
            ['name' => 'EL MOLINO', 'code' => '110', 'state_id' => $id],
            ['name' => 'FONSECA', 'code' => '279', 'state_id' => $id],
            ['name' => 'HATONUEVO', 'code' => '378', 'state_id' => $id],
            ['name' => 'LA JAGUA DEL PILAR', 'code' => '420', 'state_id' => $id],
            ['name' => 'MAICAO', 'code' => '430', 'state_id' => $id],
            ['name' => 'MANAURE', 'code' => '560', 'state_id' => $id],
            ['name' => 'SAN JUAN DEL CESAR', 'code' => '650', 'state_id' => $id],
            ['name' => 'URIBIA', 'code' => '847', 'state_id' => $id],
            ['name' => 'URUMITA', 'code' => '855', 'state_id' => $id],
            ['name' => 'VILLANUEVA', 'code' => '874', 'state_id' => $id],            
        ]);

        $id = DB::table('states')->insertGetId(
            ['code' => '47', 'name' => strToupper('Magdalena'), 'country_id' => 47]
        );

        DB::table('cities')->insert([
            ['name' => 'SANTA MARTA', 'code' => '001', 'state_id' => $id],
            ['name' => 'ALGARROBO', 'code' => '030', 'state_id' => $id],
            ['name' => 'ARACATACA', 'code' => '053', 'state_id' => $id],
            ['name' => 'ARIGUANI', 'code' => '058', 'state_id' => $id],
            ['name' => 'CERRO SAN ANTONIO', 'code' => '161', 'state_id' => $id],
            ['name' => 'CHIBOLO', 'code' => '170', 'state_id' => $id],
            ['name' => 'CIENAGA', 'code' => '189', 'state_id' => $id],
            ['name' => 'CONCORDIA', 'code' => '205', 'state_id' => $id],
            ['name' => 'EL BANCO', 'code' => '245', 'state_id' => $id],
            ['name' => 'EL PIÑON', 'code' => '258', 'state_id' => $id],
            ['name' => 'EL RETEN', 'code' => '268', 'state_id' => $id],
            ['name' => 'FUNDACION', 'code' => '288', 'state_id' => $id],
            ['name' => 'GUAMAL', 'code' => '318', 'state_id' => $id],
            ['name' => 'NUEVA GRANADA', 'code' => '460', 'state_id' => $id],
            ['name' => 'PEDRAZA', 'code' => '541', 'state_id' => $id],
            ['name' => 'PIJIÑO DEL CARMEN', 'code' => '545', 'state_id' => $id],
            ['name' => 'PIVIJAY', 'code' => '551', 'state_id' => $id],
            ['name' => 'PLATO', 'code' => '555', 'state_id' => $id],
            ['name' => 'PUEBLOVIEJO', 'code' => '570', 'state_id' => $id],
            ['name' => 'REMOLINO', 'code' => '605', 'state_id' => $id],
            ['name' => 'SABANAS DE SAN ANGEL', 'code' => '660', 'state_id' => $id],
            ['name' => 'SALAMINA', 'code' => '675', 'state_id' => $id],
            ['name' => 'SAN SEBASTIAN DE BUENAVISTA', 'code' => '692', 'state_id' => $id],
            ['name' => 'SAN ZENON', 'code' => '703', 'state_id' => $id],
            ['name' => 'SANTA ANA', 'code' => '707', 'state_id' => $id],
            ['name' => 'SANTA BARBARA DE PINTO', 'code' => '720', 'state_id' => $id],
            ['name' => 'SITIONUEVO', 'code' => '745', 'state_id' => $id],
            ['name' => 'TENERIFE', 'code' => '798', 'state_id' => $id],
            ['name' => 'ZAPAYAN', 'code' => '960', 'state_id' => $id],
            ['name' => 'ZONA BANANERA', 'code' => '980', 'state_id' => $id],
        ]);

        $id = DB::table('states')->insertGetId(
            ['code' => '50', 'name' => strToupper('Meta'), 'country_id' => 47]
        );

        DB::table('cities')->insert([
            ['name' => 'VILLAVICENCIO', 'code' => '001', 'state_id' => $id],
            ['name' => 'ACACIAS', 'code' => '006', 'state_id' => $id],
            ['name' => 'BARRANCA DE UPIA', 'code' => '110', 'state_id' => $id],
            ['name' => 'CABUYARO', 'code' => '124', 'state_id' => $id],
            ['name' => 'CASTILLA LA NUEVA', 'code' => '150', 'state_id' => $id],
            ['name' => 'CUBARRAL', 'code' => '223', 'state_id' => $id],
            ['name' => 'CUMARAL', 'code' => '226', 'state_id' => $id],
            ['name' => 'EL CALVARIO', 'code' => '245', 'state_id' => $id],
            ['name' => 'EL CASTILLO', 'code' => '251', 'state_id' => $id],
            ['name' => 'EL DORADO', 'code' => '270', 'state_id' => $id],
            ['name' => 'FUENTE DE ORO', 'code' => '287', 'state_id' => $id],
            ['name' => 'GRANADA', 'code' => '313', 'state_id' => $id],
            ['name' => 'GUAMAL', 'code' => '318', 'state_id' => $id],
            ['name' => 'MAPIRIPAN', 'code' => '325', 'state_id' => $id],
            ['name' => 'MESETAS', 'code' => '330', 'state_id' => $id],
            ['name' => 'LA MACARENA', 'code' => '350', 'state_id' => $id],
            ['name' => 'URIBE', 'code' => '370', 'state_id' => $id],
            ['name' => 'LEJANIAS', 'code' => '400', 'state_id' => $id],
            ['name' => 'PUERTO CONCORDIA', 'code' => '450', 'state_id' => $id],
            ['name' => 'PUERTO GAITAN', 'code' => '568', 'state_id' => $id],
            ['name' => 'PUERTO LOPEZ', 'code' => '573', 'state_id' => $id],
            ['name' => 'PUERTO LLERAS', 'code' => '577', 'state_id' => $id],
            ['name' => 'PUERTO RICO', 'code' => '590', 'state_id' => $id],
            ['name' => 'RESTREPO', 'code' => '606', 'state_id' => $id],
            ['name' => 'SAN CARLOS DE GUAROA', 'code' => '680', 'state_id' => $id],
            ['name' => 'SAN JUAN DE ARAMA', 'code' => '683', 'state_id' => $id],
            ['name' => 'SAN JUANITO', 'code' => '686', 'state_id' => $id],
            ['name' => 'SAN MARTIN', 'code' => '689', 'state_id' => $id],
            ['name' => 'VISTAHERMOSA', 'code' => '711', 'state_id' => $id],
        ]);

        $id = DB::table('states')->insertGetId(
            ['code' => '52', 'name' => strToupper('Nariño'), 'country_id' => 47]
        );

        DB::table('cities')->insert([
            ['name' => 'PASTO', 'code' => '001', 'state_id' => $id],
            ['name' => 'ALBAN', 'code' => '019', 'state_id' => $id],
            ['name' => 'ALDANA', 'code' => '022', 'state_id' => $id],
            ['name' => 'ANCUYA', 'code' => '036', 'state_id' => $id],
            ['name' => 'ARBOLEDA', 'code' => '051', 'state_id' => $id],
            ['name' => 'BARBACOAS', 'code' => '079', 'state_id' => $id],
            ['name' => 'BELEN', 'code' => '083', 'state_id' => $id],
            ['name' => 'BUESACO', 'code' => '110', 'state_id' => $id],
            ['name' => 'COLON', 'code' => '203', 'state_id' => $id],
            ['name' => 'CONSACA', 'code' => '207', 'state_id' => $id],
            ['name' => 'CONTADERO', 'code' => '210', 'state_id' => $id],
            ['name' => 'CORDOBA', 'code' => '215', 'state_id' => $id],
            ['name' => 'CUASPUD', 'code' => '224', 'state_id' => $id],
            ['name' => 'CUMBAL', 'code' => '227', 'state_id' => $id],
            ['name' => 'CUMBITARA', 'code' => '233', 'state_id' => $id],
            ['name' => 'CHACHAGÜI', 'code' => '240', 'state_id' => $id],
            ['name' => 'EL CHARCO', 'code' => '250', 'state_id' => $id],
            ['name' => 'EL PEÑOL', 'code' => '254', 'state_id' => $id],
            ['name' => 'EL ROSARIO', 'code' => '256', 'state_id' => $id],
            ['name' => 'EL TABLON DE GOMEZ', 'code' => '258', 'state_id' => $id],
            ['name' => 'EL TAMBO', 'code' => '260', 'state_id' => $id],
            ['name' => 'FUNES', 'code' => '287', 'state_id' => $id],
            ['name' => 'GUACHUCAL', 'code' => '317', 'state_id' => $id],
            ['name' => 'GUAITARILLA', 'code' => '320', 'state_id' => $id],
            ['name' => 'GUALMATAN', 'code' => '323', 'state_id' => $id],
            ['name' => 'ILES', 'code' => '352', 'state_id' => $id],
            ['name' => 'IMUES', 'code' => '354', 'state_id' => $id],
            ['name' => 'IPIALES', 'code' => '356', 'state_id' => $id],
            ['name' => 'LA CRUZ', 'code' => '378', 'state_id' => $id],
            ['name' => 'LA FLORIDA', 'code' => '381', 'state_id' => $id],
            ['name' => 'LA LLANADA', 'code' => '385', 'state_id' => $id],
            ['name' => 'LA TOLA', 'code' => '390', 'state_id' => $id],
            ['name' => 'LA UNION', 'code' => '399', 'state_id' => $id],
            ['name' => 'LEIVA', 'code' => '405', 'state_id' => $id],
            ['name' => 'LINARES', 'code' => '411', 'state_id' => $id],
            ['name' => 'LOS ANDES', 'code' => '418', 'state_id' => $id],
            ['name' => 'MAGÜI', 'code' => '427', 'state_id' => $id],
            ['name' => 'MALLAMA', 'code' => '435', 'state_id' => $id],
            ['name' => 'MOSQUERA', 'code' => '473', 'state_id' => $id],
            ['name' => 'NARIÑO', 'code' => '480', 'state_id' => $id],
            ['name' => 'OLAYA HERRERA', 'code' => '490', 'state_id' => $id],
            ['name' => 'OSPINA', 'code' => '506', 'state_id' => $id],
            ['name' => 'FRANCISCO PIZARRO', 'code' => '520', 'state_id' => $id],
            ['name' => 'POLICARPA', 'code' => '540', 'state_id' => $id],
            ['name' => 'POTOSI', 'code' => '560', 'state_id' => $id],
            ['name' => 'PROVIDENCIA', 'code' => '565', 'state_id' => $id],
            ['name' => 'PUERRES', 'code' => '573', 'state_id' => $id],
            ['name' => 'PUPIALES', 'code' => '585', 'state_id' => $id],
            ['name' => 'RICAURTE', 'code' => '612', 'state_id' => $id],
            ['name' => 'ROBERTO PAYAN', 'code' => '621', 'state_id' => $id],
            ['name' => 'SAMANIEGO', 'code' => '678', 'state_id' => $id],
            ['name' => 'SANDONA', 'code' => '683', 'state_id' => $id],
            ['name' => 'SAN BERNARDO', 'code' => '685', 'state_id' => $id],
            ['name' => 'SAN LORENZO', 'code' => '687', 'state_id' => $id],
            ['name' => 'SAN PABLO', 'code' => '693', 'state_id' => $id],
            ['name' => 'SAN PEDRO DE CARTAGO', 'code' => '694', 'state_id' => $id],
            ['name' => 'SANTA BARBARA', 'code' => '696', 'state_id' => $id],
            ['name' => 'SANTACRUZ', 'code' => '699', 'state_id' => $id],
            ['name' => 'SAPUYES', 'code' => '720', 'state_id' => $id],
            ['name' => 'TAMINANGO', 'code' => '786', 'state_id' => $id],
            ['name' => 'TANGUA', 'code' => '788', 'state_id' => $id],
            ['name' => 'TUMACO', 'code' => '835', 'state_id' => $id],
            ['name' => 'TUQUERRES', 'code' => '838', 'state_id' => $id],
            ['name' => 'YACUANQUER', 'code' => '885', 'state_id' => $id],
        ]);

        $id = DB::table('states')->insertGetId(
            ['code' => '54', 'name' => strToupper('Norte de Santander'), 'country_id' => 47]
        );

        DB::table('cities')->insert([
            ['name' => 'CUCUTA', 'code' => '001', 'state_id' => $id],
            ['name' => 'ABREGO', 'code' => '003', 'state_id' => $id],
            ['name' => 'ARBOLEDAS', 'code' => '051', 'state_id' => $id],
            ['name' => 'BOCHALEMA', 'code' => '099', 'state_id' => $id],
            ['name' => 'BUCARASICA', 'code' => '109', 'state_id' => $id],
            ['name' => 'CACOTA', 'code' => '125', 'state_id' => $id],
            ['name' => 'CACHIRA', 'code' => '128', 'state_id' => $id],
            ['name' => 'CHINACOTA', 'code' => '172', 'state_id' => $id],
            ['name' => 'CHITAGA', 'code' => '174', 'state_id' => $id],
            ['name' => 'CONVENCION', 'code' => '206', 'state_id' => $id],
            ['name' => 'CUCUTILLA', 'code' => '223', 'state_id' => $id],
            ['name' => 'DURANIA', 'code' => '239', 'state_id' => $id],
            ['name' => 'EL CARMEN', 'code' => '245', 'state_id' => $id],
            ['name' => 'EL TARRA', 'code' => '250', 'state_id' => $id],
            ['name' => 'EL ZULIA', 'code' => '261', 'state_id' => $id],
            ['name' => 'GRAMALOTE', 'code' => '313', 'state_id' => $id],
            ['name' => 'HACARI', 'code' => '344', 'state_id' => $id],
            ['name' => 'HERRAN', 'code' => '347', 'state_id' => $id],
            ['name' => 'LABATECA', 'code' => '377', 'state_id' => $id],
            ['name' => 'LA ESPERANZA', 'code' => '385', 'state_id' => $id],
            ['name' => 'LA PLAYA', 'code' => '398', 'state_id' => $id],
            ['name' => 'LOS PATIOS', 'code' => '405', 'state_id' => $id],
            ['name' => 'LOURDES', 'code' => '418', 'state_id' => $id],
            ['name' => 'MUTISCUA', 'code' => '480', 'state_id' => $id],
            ['name' => 'OCAÑA', 'code' => '498', 'state_id' => $id],
            ['name' => 'PAMPLONA', 'code' => '518', 'state_id' => $id],
            ['name' => 'PAMPLONITA', 'code' => '520', 'state_id' => $id],
            ['name' => 'PUERTO SANTANDER', 'code' => '553', 'state_id' => $id],
            ['name' => 'RAGONVALIA', 'code' => '599', 'state_id' => $id],
            ['name' => 'SALAZAR', 'code' => '660', 'state_id' => $id],
            ['name' => 'SAN CALIXTO', 'code' => '670', 'state_id' => $id],
            ['name' => 'SAN CAYETANO', 'code' => '673', 'state_id' => $id],
            ['name' => 'SANTIAGO', 'code' => '680', 'state_id' => $id],
            ['name' => 'SARDINATA', 'code' => '720', 'state_id' => $id],
            ['name' => 'SILOS', 'code' => '743', 'state_id' => $id],
            ['name' => 'TEORAMA', 'code' => '800', 'state_id' => $id],
            ['name' => 'TIBU', 'code' => '810', 'state_id' => $id],
            ['name' => 'TOLEDO', 'code' => '820', 'state_id' => $id],
            ['name' => 'VILLA CARO', 'code' => '871', 'state_id' => $id],
            ['name' => 'VILLA DEL ROSARIO', 'code' => '874', 'state_id' => $id],
        ]);

        $id = DB::table('states')->insertGetId(
            ['code' => '63', 'name' => strToupper('Quindio'), 'country_id' => 47]
        );

        DB::table('cities')->insert([
            ['name' => 'ARMENIA', 'code' => '001', 'state_id' => $id],
            ['name' => 'BUENAVISTA', 'code' => '111', 'state_id' => $id],
            ['name' => 'CALARCA', 'code' => '130', 'state_id' => $id],
            ['name' => 'CIRCASIA', 'code' => '190', 'state_id' => $id],
            ['name' => 'CORDOBA', 'code' => '212', 'state_id' => $id],
            ['name' => 'FILANDIA', 'code' => '272', 'state_id' => $id],
            ['name' => 'GENOVA', 'code' => '302', 'state_id' => $id],
            ['name' => 'LA TEBAIDA', 'code' => '401', 'state_id' => $id],
            ['name' => 'MONTENEGRO', 'code' => '470', 'state_id' => $id],
            ['name' => 'PIJAO', 'code' => '548', 'state_id' => $id],
            ['name' => 'QUIMBAYA', 'code' => '594', 'state_id' => $id],
            ['name' => 'SALENTO', 'code' => '690', 'state_id' => $id],
        ]);

        $id = DB::table('states')->insertGetId(
            ['code' => '66', 'name' => strToupper('Risaralda'), 'country_id' => 47]
        );

        DB::table('cities')->insert([
            ['name' => 'PEREIRA', 'code' => '001', 'state_id' => $id],
            ['name' => 'APIA', 'code' => '045', 'state_id' => $id],
            ['name' => 'BALBOA', 'code' => '075', 'state_id' => $id],
            ['name' => 'BELEN DE UMBRIA', 'code' => '088', 'state_id' => $id],
            ['name' => 'DOSQUEBRADAS', 'code' => '170', 'state_id' => $id],
            ['name' => 'GUATICA', 'code' => '318', 'state_id' => $id],
            ['name' => 'LA CELIA', 'code' => '383', 'state_id' => $id],
            ['name' => 'LA VIRGINIA', 'code' => '400', 'state_id' => $id],
            ['name' => 'MARSELLA', 'code' => '440', 'state_id' => $id],
            ['name' => 'MISTRATO', 'code' => '456', 'state_id' => $id],
            ['name' => 'PUEBLO RICO', 'code' => '572', 'state_id' => $id],
            ['name' => 'QUINCHIA', 'code' => '594', 'state_id' => $id],
            ['name' => 'SANTA ROSA DE CABAL', 'code' => '682', 'state_id' => $id],
            ['name' => 'SANTUARIO', 'code' => '687', 'state_id' => $id],
        ]);

        $id = DB::table('states')->insertGetId(
            ['code' => '68', 'name' => strToupper('Santander'), 'country_id' => 47]
        );

        DB::table('cities')->insert([
            ['name' => 'BUCARAMANGA', 'code' => '001', 'state_id' => $id],
            ['name' => 'AGUADA', 'code' => '013', 'state_id' => $id],
            ['name' => 'ALBANIA', 'code' => '020', 'state_id' => $id],
            ['name' => 'ARATOCA', 'code' => '051', 'state_id' => $id],
            ['name' => 'BARBOSA', 'code' => '077', 'state_id' => $id],
            ['name' => 'BARICHARA', 'code' => '079', 'state_id' => $id],
            ['name' => 'BARRANCABERMEJA', 'code' => '081', 'state_id' => $id],
            ['name' => 'BETULIA', 'code' => '092', 'state_id' => $id],
            ['name' => 'BOLIVAR', 'code' => '101', 'state_id' => $id],
            ['name' => 'CABRERA', 'code' => '121', 'state_id' => $id],
            ['name' => 'CALIFORNIA', 'code' => '132', 'state_id' => $id],
            ['name' => 'CAPITANEJO', 'code' => '147', 'state_id' => $id],
            ['name' => 'CARCASI', 'code' => '152', 'state_id' => $id],
            ['name' => 'CEPITA', 'code' => '160', 'state_id' => $id],
            ['name' => 'CERRITO', 'code' => '162', 'state_id' => $id],
            ['name' => 'CHARALA', 'code' => '167', 'state_id' => $id],
            ['name' => 'CHARTA', 'code' => '169', 'state_id' => $id],
            ['name' => 'CHIMA', 'code' => '176', 'state_id' => $id],
            ['name' => 'CHIPATA', 'code' => '179', 'state_id' => $id],
            ['name' => 'CIMITARRA', 'code' => '190', 'state_id' => $id],
            ['name' => 'CONCEPCION', 'code' => '207', 'state_id' => $id],
            ['name' => 'CONFINES', 'code' => '209', 'state_id' => $id],
            ['name' => 'CONTRATACION', 'code' => '211', 'state_id' => $id],
            ['name' => 'COROMORO', 'code' => '217', 'state_id' => $id],
            ['name' => 'CURITI', 'code' => '229', 'state_id' => $id],
            ['name' => 'EL CARMEN DE CHUCURI', 'code' => '235', 'state_id' => $id],
            ['name' => 'EL GUACAMAYO', 'code' => '245', 'state_id' => $id],
            ['name' => 'EL PEÑON', 'code' => '250', 'state_id' => $id],
            ['name' => 'EL PLAYON', 'code' => '255', 'state_id' => $id],
            ['name' => 'ENCINO', 'code' => '264', 'state_id' => $id],
            ['name' => 'ENCISO', 'code' => '266', 'state_id' => $id],
            ['name' => 'FLORIAN', 'code' => '271', 'state_id' => $id],
            ['name' => 'FLORIDABLANCA', 'code' => '276', 'state_id' => $id],
            ['name' => 'GALAN', 'code' => '296', 'state_id' => $id],
            ['name' => 'GAMBITA', 'code' => '298', 'state_id' => $id],
            ['name' => 'GIRON', 'code' => '307', 'state_id' => $id],
            ['name' => 'GUACA', 'code' => '318', 'state_id' => $id],
            ['name' => 'GUADALUPE', 'code' => '320', 'state_id' => $id],
            ['name' => 'GUAPOTA', 'code' => '322', 'state_id' => $id],
            ['name' => 'GUAVATA', 'code' => '324', 'state_id' => $id],
            ['name' => 'GÜEPSA', 'code' => '327', 'state_id' => $id],
            ['name' => 'HATO', 'code' => '344', 'state_id' => $id],
            ['name' => 'JESUS MARIA', 'code' => '368', 'state_id' => $id],
            ['name' => 'JORDAN', 'code' => '370', 'state_id' => $id],
            ['name' => 'LA BELLEZA', 'code' => '377', 'state_id' => $id],
            ['name' => 'LANDAZURI', 'code' => '385', 'state_id' => $id],
            ['name' => 'LA PAZ', 'code' => '397', 'state_id' => $id],
            ['name' => 'LEBRIJA', 'code' => '406', 'state_id' => $id],
            ['name' => 'LOS SANTOS', 'code' => '418', 'state_id' => $id],
            ['name' => 'MACARAVITA', 'code' => '425', 'state_id' => $id],
            ['name' => 'MALAGA', 'code' => '432', 'state_id' => $id],
            ['name' => 'MATANZA', 'code' => '444', 'state_id' => $id],
            ['name' => 'MOGOTES', 'code' => '464', 'state_id' => $id],
            ['name' => 'MOLAGAVITA', 'code' => '468', 'state_id' => $id],
            ['name' => 'OCAMONTE', 'code' => '498', 'state_id' => $id],
            ['name' => 'OIBA', 'code' => '500', 'state_id' => $id],
            ['name' => 'ONZAGA', 'code' => '502', 'state_id' => $id],
            ['name' => 'PALMAR', 'code' => '522', 'state_id' => $id],
            ['name' => 'PALMAS DEL SOCORRO', 'code' => '524', 'state_id' => $id],
            ['name' => 'PARAMO', 'code' => '533', 'state_id' => $id],
            ['name' => 'PIEDECUESTA', 'code' => '547', 'state_id' => $id],
            ['name' => 'PINCHOTE', 'code' => '549', 'state_id' => $id],
            ['name' => 'PUENTE NACIONAL', 'code' => '572', 'state_id' => $id],
            ['name' => 'PUERTO PARRA', 'code' => '573', 'state_id' => $id],
            ['name' => 'PUERTO WILCHES', 'code' => '575', 'state_id' => $id],
            ['name' => 'RIONEGRO', 'code' => '615', 'state_id' => $id],
            ['name' => 'SABANA DE TORRES', 'code' => '655', 'state_id' => $id],
            ['name' => 'SAN ANDRES', 'code' => '669', 'state_id' => $id],
            ['name' => 'SAN BENITO', 'code' => '673', 'state_id' => $id],
            ['name' => 'SAN GIL', 'code' => '679', 'state_id' => $id],
            ['name' => 'SAN JOAQUIN', 'code' => '682', 'state_id' => $id],
            ['name' => 'SAN JOSE DE MIRANDA', 'code' => '684', 'state_id' => $id],
            ['name' => 'SAN MIGUEL', 'code' => '686', 'state_id' => $id],
            ['name' => 'SAN VICENTE DE CHUCURI', 'code' => '689', 'state_id' => $id],
            ['name' => 'SANTA BARBARA', 'code' => '705', 'state_id' => $id],
            ['name' => 'SANTA HELENA DEL OPON', 'code' => '720', 'state_id' => $id],
            ['name' => 'SIMACOTA', 'code' => '745', 'state_id' => $id],
            ['name' => 'SOCORRO', 'code' => '755', 'state_id' => $id],
            ['name' => 'SUAITA', 'code' => '770', 'state_id' => $id],
            ['name' => 'SUCRE', 'code' => '773', 'state_id' => $id],
            ['name' => 'SURATA', 'code' => '780', 'state_id' => $id],
            ['name' => 'TONA', 'code' => '820', 'state_id' => $id],
            ['name' => 'VALLE DE SAN JOSE', 'code' => '855', 'state_id' => $id],
            ['name' => 'VELEZ', 'code' => '861', 'state_id' => $id],
            ['name' => 'VETAS', 'code' => '867', 'state_id' => $id],
            ['name' => 'VILLANUEVA', 'code' => '872', 'state_id' => $id],
            ['name' => 'ZAPATOCA', 'code' => '895', 'state_id' => $id],
        ]);

        $id = DB::table('states')->insertGetId(
            ['code' => '70', 'name' => strToupper('Sucre'), 'country_id' => 47]
        );

        DB::table('cities')->insert([
            ['name' => 'SINCELEJO', 'code' => '001', 'state_id' => $id],
            ['name' => 'BUENAVISTA', 'code' => '110', 'state_id' => $id],
            ['name' => 'CAIMITO', 'code' => '124', 'state_id' => $id],
            ['name' => 'COLOSO', 'code' => '204', 'state_id' => $id],
            ['name' => 'COROZAL', 'code' => '215', 'state_id' => $id],
            ['name' => 'COVEÑAS', 'code' => '221', 'state_id' => $id],
            ['name' => 'CHALAN', 'code' => '230', 'state_id' => $id],
            ['name' => 'EL ROBLE', 'code' => '233', 'state_id' => $id],
            ['name' => 'GALERAS', 'code' => '235', 'state_id' => $id],
            ['name' => 'GUARANDA', 'code' => '265', 'state_id' => $id],
            ['name' => 'LA UNION', 'code' => '400', 'state_id' => $id],
            ['name' => 'LOS PALMITOS', 'code' => '418', 'state_id' => $id],
            ['name' => 'MAJAGUAL', 'code' => '429', 'state_id' => $id],
            ['name' => 'MORROA', 'code' => '473', 'state_id' => $id],
            ['name' => 'OVEJAS', 'code' => '508', 'state_id' => $id],
            ['name' => 'PALMITO', 'code' => '523', 'state_id' => $id],
            ['name' => 'SAMPUES', 'code' => '670', 'state_id' => $id],
            ['name' => 'SAN BENITO ABAD', 'code' => '678', 'state_id' => $id],
            ['name' => 'SAN JUAN DE BETULIA', 'code' => '702', 'state_id' => $id],
            ['name' => 'SAN MARCOS', 'code' => '708', 'state_id' => $id],
            ['name' => 'SAN ONOFRE', 'code' => '713', 'state_id' => $id],
            ['name' => 'SAN PEDRO', 'code' => '717', 'state_id' => $id],
            ['name' => 'SINCE', 'code' => '742', 'state_id' => $id],
            ['name' => 'SUCRE', 'code' => '771', 'state_id' => $id],
            ['name' => 'SANTIAGO DE TOLU', 'code' => '820', 'state_id' => $id],
            ['name' => 'TOLU VIEJO', 'code' => '823', 'state_id' => $id],
        ]);

        $id = DB::table('states')->insertGetId(
            ['code' => '73', 'name' => strToupper('Tolima'), 'country_id' => 47]
        );

        DB::table('cities')->insert([
            ['name' => 'IBAGUE', 'code' => '001', 'state_id' => $id],
            ['name' => 'ALPUJARRA', 'code' => '024', 'state_id' => $id],
            ['name' => 'ALVARADO', 'code' => '026', 'state_id' => $id],
            ['name' => 'AMBALEMA', 'code' => '030', 'state_id' => $id],
            ['name' => 'ANZOATEGUI', 'code' => '043', 'state_id' => $id],
            ['name' => 'ARMERO', 'code' => '055', 'state_id' => $id],
            ['name' => 'ATACO', 'code' => '067', 'state_id' => $id],
            ['name' => 'CAJAMARCA', 'code' => '124', 'state_id' => $id],
            ['name' => 'CARMEN DE APICALA', 'code' => '148', 'state_id' => $id],
            ['name' => 'CASABIANCA', 'code' => '152', 'state_id' => $id],
            ['name' => 'CHAPARRAL', 'code' => '168', 'state_id' => $id],
            ['name' => 'COELLO', 'code' => '200', 'state_id' => $id],
            ['name' => 'COYAIMA', 'code' => '217', 'state_id' => $id],
            ['name' => 'CUNDAY', 'code' => '226', 'state_id' => $id],
            ['name' => 'DOLORES', 'code' => '236', 'state_id' => $id],
            ['name' => 'ESPINAL', 'code' => '268', 'state_id' => $id],
            ['name' => 'FALAN', 'code' => '270', 'state_id' => $id],
            ['name' => 'FLANDES', 'code' => '275', 'state_id' => $id],
            ['name' => 'FRESNO', 'code' => '283', 'state_id' => $id],
            ['name' => 'GUAMO', 'code' => '319', 'state_id' => $id],
            ['name' => 'HERVEO', 'code' => '347', 'state_id' => $id],
            ['name' => 'HONDA', 'code' => '349', 'state_id' => $id],
            ['name' => 'ICONONZO', 'code' => '352', 'state_id' => $id],
            ['name' => 'LERIDA', 'code' => '408', 'state_id' => $id],
            ['name' => 'LIBANO', 'code' => '411', 'state_id' => $id],
            ['name' => 'MARIQUITA', 'code' => '443', 'state_id' => $id],
            ['name' => 'MELGAR', 'code' => '449', 'state_id' => $id],
            ['name' => 'MURILLO', 'code' => '461', 'state_id' => $id],
            ['name' => 'NATAGAIMA', 'code' => '483', 'state_id' => $id],
            ['name' => 'ORTEGA', 'code' => '504', 'state_id' => $id],
            ['name' => 'PALOCABILDO', 'code' => '520', 'state_id' => $id],
            ['name' => 'PIEDRAS', 'code' => '547', 'state_id' => $id],
            ['name' => 'PLANADAS', 'code' => '555', 'state_id' => $id],
            ['name' => 'PRADO', 'code' => '563', 'state_id' => $id],
            ['name' => 'PURIFICACION', 'code' => '585', 'state_id' => $id],
            ['name' => 'RIOBLANCO', 'code' => '616', 'state_id' => $id],
            ['name' => 'RONCESVALLES', 'code' => '622', 'state_id' => $id],
            ['name' => 'ROVIRA', 'code' => '624', 'state_id' => $id],
            ['name' => 'SALDAÑA', 'code' => '671', 'state_id' => $id],
            ['name' => 'SAN ANTONIO', 'code' => '675', 'state_id' => $id],
            ['name' => 'SAN LUIS', 'code' => '678', 'state_id' => $id],
            ['name' => 'SANTA ISABEL', 'code' => '686', 'state_id' => $id],
            ['name' => 'SUAREZ', 'code' => '770', 'state_id' => $id],
            ['name' => 'VALLE DE SAN JUAN', 'code' => '854', 'state_id' => $id],
            ['name' => 'VENADILLO', 'code' => '861', 'state_id' => $id],
            ['name' => 'VILLAHERMOSA', 'code' => '870', 'state_id' => $id],
            ['name' => 'VILLARRICA', 'code' => '873', 'state_id' => $id],
        ]);

        $id = DB::table('states')->insertGetId(
            ['code' => '76', 'name' => strToupper('Valle del Cauca'), 'country_id' => 47]
        );

        DB::table('cities')->insert([
            ['name' => 'CALI', 'code' => '001', 'state_id' => $id],
            ['name' => 'ALCALA', 'code' => '020', 'state_id' => $id],
            ['name' => 'ANDALUCIA', 'code' => '036', 'state_id' => $id],
            ['name' => 'ANSERMANUEVO', 'code' => '041', 'state_id' => $id],
            ['name' => 'ARGELIA', 'code' => '054', 'state_id' => $id],
            ['name' => 'BOLIVAR', 'code' => '100', 'state_id' => $id],
            ['name' => 'BUENAVENTURA', 'code' => '109', 'state_id' => $id],
            ['name' => 'GUADALAJARA DE BUGA', 'code' => '111', 'state_id' => $id],
            ['name' => 'BUGALAGRANDE', 'code' => '113', 'state_id' => $id],
            ['name' => 'CAICEDONIA', 'code' => '122', 'state_id' => $id],
            ['name' => 'CALIMA', 'code' => '126', 'state_id' => $id],
            ['name' => 'CANDELARIA', 'code' => '130', 'state_id' => $id],
            ['name' => 'CARTAGO', 'code' => '147', 'state_id' => $id],
            ['name' => 'DAGUA', 'code' => '233', 'state_id' => $id],
            ['name' => 'EL AGUILA', 'code' => '243', 'state_id' => $id],
            ['name' => 'EL CAIRO', 'code' => '246', 'state_id' => $id],
            ['name' => 'EL CERRITO', 'code' => '248', 'state_id' => $id],
            ['name' => 'EL DOVIO', 'code' => '250', 'state_id' => $id],
            ['name' => 'FLORIDA', 'code' => '275', 'state_id' => $id],
            ['name' => 'GINEBRA', 'code' => '306', 'state_id' => $id],
            ['name' => 'GUACARI', 'code' => '318', 'state_id' => $id],
            ['name' => 'JAMUNDI', 'code' => '364', 'state_id' => $id],
            ['name' => 'LA CUMBRE', 'code' => '377', 'state_id' => $id],
            ['name' => 'LA UNION', 'code' => '400', 'state_id' => $id],
            ['name' => 'LA VICTORIA', 'code' => '403', 'state_id' => $id],
            ['name' => 'OBANDO', 'code' => '497', 'state_id' => $id],
            ['name' => 'PALMIRA', 'code' => '520', 'state_id' => $id],
            ['name' => 'PRADERA', 'code' => '563', 'state_id' => $id],
            ['name' => 'RESTREPO', 'code' => '606', 'state_id' => $id],
            ['name' => 'RIOFRIO', 'code' => '616', 'state_id' => $id],
            ['name' => 'ROLDANILLO', 'code' => '622', 'state_id' => $id],
            ['name' => 'SAN PEDRO', 'code' => '670', 'state_id' => $id],
            ['name' => 'SEVILLA', 'code' => '736', 'state_id' => $id],
            ['name' => 'TORO', 'code' => '823', 'state_id' => $id],
            ['name' => 'TRUJILLO', 'code' => '828', 'state_id' => $id],
            ['name' => 'TULUA', 'code' => '834', 'state_id' => $id],
            ['name' => 'ULLOA', 'code' => '845', 'state_id' => $id],
            ['name' => 'VERSALLES', 'code' => '863', 'state_id' => $id],
            ['name' => 'VIJES', 'code' => '869', 'state_id' => $id],
            ['name' => 'YOTOCO', 'code' => '890', 'state_id' => $id],
            ['name' => 'YUMBO', 'code' => '892', 'state_id' => $id],
            ['name' => 'ZARZAL', 'code' => '895', 'state_id' => $id],
        ]);

        $id = DB::table('states')->insertGetId(
            ['code' => '81', 'name' => strToupper('Arauca'), 'country_id' => 47]
        );

        DB::table('cities')->insert([
            ['name' => 'ARAUCA', 'code' => '001', 'state_id' => $id],
            ['name' => 'ARAUQUITA', 'code' => '065', 'state_id' => $id],
            ['name' => 'CRAVO NORTE', 'code' => '220', 'state_id' => $id],
            ['name' => 'FORTUL', 'code' => '300', 'state_id' => $id],
            ['name' => 'PUERTO RONDON', 'code' => '591', 'state_id' => $id],
            ['name' => 'SARAVENA', 'code' => '736', 'state_id' => $id],
            ['name' => 'TAME', 'code' => '794', 'state_id' => $id],
        ]);

        $id = DB::table('states')->insertGetId(
            ['code' => '85', 'name' => strToupper('Casanare'), 'country_id' => 47]
        );

        DB::table('cities')->insert([
            ['name' => 'YOPAL', 'code' => '001', 'state_id' => $id],
            ['name' => 'AGUAZUL', 'code' => '010', 'state_id' => $id],
            ['name' => 'CHAMEZA', 'code' => '015', 'state_id' => $id],
            ['name' => 'HATO COROZAL', 'code' => '125', 'state_id' => $id],
            ['name' => 'LA SALINA', 'code' => '136', 'state_id' => $id],
            ['name' => 'MANI', 'code' => '139', 'state_id' => $id],
            ['name' => 'MONTERREY', 'code' => '162', 'state_id' => $id],
            ['name' => 'NUNCHIA', 'code' => '225', 'state_id' => $id],
            ['name' => 'OROCUE', 'code' => '230', 'state_id' => $id],
            ['name' => 'PAZ DE ARIPORO', 'code' => '250', 'state_id' => $id],
            ['name' => 'PORE', 'code' => '263', 'state_id' => $id],
            ['name' => 'RECETOR', 'code' => '279', 'state_id' => $id],
            ['name' => 'SABANALARGA', 'code' => '300', 'state_id' => $id],
            ['name' => 'SACAMA', 'code' => '315', 'state_id' => $id],
            ['name' => 'SAN LUIS DE PALENQUE', 'code' => '325', 'state_id' => $id],
            ['name' => 'TAMARA', 'code' => '400', 'state_id' => $id],
            ['name' => 'TAURAMENA', 'code' => '410', 'state_id' => $id],
            ['name' => 'TRINIDAD', 'code' => '430', 'state_id' => $id],
            ['name' => 'VILLANUEVA', 'code' => '440', 'state_id' => $id],
        ]);

        $id = DB::table('states')->insertGetId(
            ['code' => '86', 'name' => strToupper('Putumayo'), 'country_id' => 47]
        );

        DB::table('cities')->insert([
            ['name' => 'MOCOA', 'code' => '001', 'state_id' => $id],
            ['name' => 'COLON', 'code' => '219', 'state_id' => $id],
            ['name' => 'ORITO', 'code' => '320', 'state_id' => $id],
            ['name' => 'PUERTO ASIS', 'code' => '568', 'state_id' => $id],
            ['name' => 'PUERTO CAICEDO', 'code' => '569', 'state_id' => $id],
            ['name' => 'PUERTO GUZMAN', 'code' => '571', 'state_id' => $id],
            ['name' => 'LEGUIZAMO', 'code' => '573', 'state_id' => $id],
            ['name' => 'SIBUNDOY', 'code' => '749', 'state_id' => $id],
            ['name' => 'SAN FRANCISCO', 'code' => '755', 'state_id' => $id],
            ['name' => 'SAN MIGUEL', 'code' => '757', 'state_id' => $id],
            ['name' => 'SANTIAGO', 'code' => '760', 'state_id' => $id],
            ['name' => 'VALLE DEL GUAMUEZ', 'code' => '865', 'state_id' => $id],
            ['name' => 'VILLAGARZON', 'code' => '885', 'state_id' => $id],
        ]);

        $id = DB::table('states')->insertGetId(
            ['code' => '88', 'name' => strToupper('ArchipiElago de San AndrEs, Providencia y Santa Catalina'), 'country_id' => 47]
        );

        DB::table('cities')->insert([
            ['name' => 'SAN ANDRES', 'code' => '001', 'state_id' => $id],
            ['name' => 'PROVIDENCIA', 'code' => '564', 'state_id' => $id],
        ]);

        $id = DB::table('states')->insertGetId(
            ['code' => '91', 'name' => strToupper('Amazonas'), 'country_id' => 47]
        );

        DB::table('cities')->insert([
            ['name' => 'LETICIA', 'code' => '001', 'state_id' => $id],
            ['name' => 'EL ENCANTO', 'code' => '263', 'state_id' => $id],
            ['name' => 'LA CHORRERA', 'code' => '405', 'state_id' => $id],
            ['name' => 'LA PEDRERA', 'code' => '407', 'state_id' => $id],
            ['name' => 'LA VICTORIA', 'code' => '430', 'state_id' => $id],
            ['name' => 'MIRITI - PARANA', 'code' => '460', 'state_id' => $id],
            ['name' => 'PUERTO ALEGRIA', 'code' => '530', 'state_id' => $id],
            ['name' => 'PUERTO ARICA', 'code' => '536', 'state_id' => $id],
            ['name' => 'PUERTO NARIÑO', 'code' => '540', 'state_id' => $id],
            ['name' => 'PUERTO SANTANDER', 'code' => '669', 'state_id' => $id],
            ['name' => 'TARAPACA', 'code' => '798', 'state_id' => $id],
        ]);

        $id = DB::table('states')->insertGetId(
            ['code' => '94', 'name' => strToupper('GuainIa'), 'country_id' => 47]
        );

        DB::table('cities')->insert([
            ['name' => 'INIRIDA', 'code' => '001', 'state_id' => $id],
            ['name' => 'BARRANCO MINAS', 'code' => '343', 'state_id' => $id],
            ['name' => 'MAPIRIPANA', 'code' => '663', 'state_id' => $id],
            ['name' => 'SAN FELIPE', 'code' => '883', 'state_id' => $id],
            ['name' => 'PUERTO COLOMBIA', 'code' => '884', 'state_id' => $id],
            ['name' => 'LA GUADALUPE', 'code' => '885', 'state_id' => $id],
            ['name' => 'CACAHUAL', 'code' => '886', 'state_id' => $id],
            ['name' => 'PANA PANA', 'code' => '887', 'state_id' => $id],
            ['name' => 'MORICHAL', 'code' => '888', 'state_id' => $id],
        ]);

        $id = DB::table('states')->insertGetId(
            ['code' => '95', 'name' => strToupper('Guaviare'), 'country_id' => 47]
        );

        DB::table('cities')->insert([
            ['name' => 'SAN JOSE DEL GUAVIARE', 'code' => '001', 'state_id' => $id],
            ['name' => 'CALAMAR', 'code' => '015', 'state_id' => $id],
            ['name' => 'EL RETORNO', 'code' => '025', 'state_id' => $id],
            ['name' => 'MIRAFLORES', 'code' => '200', 'state_id' => $id],
        ]);

        $id = DB::table('states')->insertGetId(
            ['code' => '97', 'name' => strToupper('VaupEs'), 'country_id' => 47]
        );

        DB::table('cities')->insert([
            ['name' => 'MITU', 'code' => '001', 'state_id' => $id],
            ['name' => 'CARURU', 'code' => '161', 'state_id' => $id],
            ['name' => 'PACOA', 'code' => '511', 'state_id' => $id],
            ['name' => 'TARAIRA', 'code' => '666', 'state_id' => $id],
            ['name' => 'PAPUNAUA', 'code' => '777', 'state_id' => $id],
            ['name' => 'YAVARATE', 'code' => '889', 'state_id' => $id],
        ]);

        $id = DB::table('states')->insertGetId(
            ['code' => '99', 'name' => strToupper('Vichada'), 'country_id' => 47]
        );

        DB::table('cities')->insert([
            ['name' => 'PUERTO CARREÑO', 'code' => '001', 'state_id' => $id],
            ['name' => 'LA PRIMAVERA', 'code' => '524', 'state_id' => $id],
            ['name' => 'SANTA ROSALIA', 'code' => '624', 'state_id' => $id],
            ['name' => 'CUMARIBO', 'code' => '773', 'state_id' => $id],
        ]);
    }
}
