<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->insert([
            ['code' => 'AF', 'name' => strToupper('Afghanistan')],
            ['code' => 'AL', 'name' => strToupper('Albania')],
            ['code' => 'DZ', 'name' => strToupper('Algeria')],
            ['code' => 'AS', 'name' => strToupper('American Samoa')],
            ['code' => 'AD', 'name' => strToupper('Andorra')],
            ['code' => 'AO', 'name' => strToupper('Angola')],
            ['code' => 'AI', 'name' => strToupper('Anguilla')],
            ['code' => 'AQ', 'name' => strToupper('Antarctica')],
            ['code' => 'AG', 'name' => strToupper('Antigua And Barbuda')],
            ['code' => 'AR', 'name' => strToupper('Argentina')],
            ['code' => 'AM', 'name' => strToupper('Armenia')],
            ['code' => 'AW', 'name' => strToupper('Aruba')],
            ['code' => 'AU', 'name' => strToupper('Australia')],
            ['code' => 'AT', 'name' => strToupper('Austria')],
            ['code' => 'AZ', 'name' => strToupper('Azerbaijan')],
            ['code' => 'BS', 'name' => strToupper('Bahamas')],
            ['code' => 'BH', 'name' => strToupper('Bahrain')],
            ['code' => 'BD', 'name' => strToupper('Bangladesh')],
            ['code' => 'BB', 'name' => strToupper('Barbados')],
            ['code' => 'BY', 'name' => strToupper('Belarus')],
            ['code' => 'BE', 'name' => strToupper('Belgium')],
            ['code' => 'BZ', 'name' => strToupper('Belize')],
            ['code' => 'BJ', 'name' => strToupper('Benin')],
            ['code' => 'BM', 'name' => strToupper('Bermuda')],
            ['code' => 'BT', 'name' => strToupper('Bhutan')],
            ['code' => 'BO', 'name' => strToupper('Bolivia')],
            ['code' => 'BA', 'name' => strToupper('Bosnia And Herzegovina')],
            ['code' => 'BW', 'name' => strToupper('Botswana')],
            ['code' => 'BV', 'name' => strToupper('Bouvet Island')],
            ['code' => 'BR', 'name' => strToupper('Brazil')],
            ['code' => 'IO', 'name' => strToupper('British Indian Ocean Territory')],
            ['code' => 'BN', 'name' => strToupper('Brunei Darussalam')],
            ['code' => 'BG', 'name' => strToupper('Bulgaria')],
            ['code' => 'BF', 'name' => strToupper('Burkina Faso')],
            ['code' => 'BI', 'name' => strToupper('Burundi')],
            ['code' => 'KH', 'name' => strToupper('Cambodia')],
            ['code' => 'CM', 'name' => strToupper('Cameroon')],
            ['code' => 'CA', 'name' => strToupper('Canada')],
            ['code' => 'CV', 'name' => strToupper('Cape Verde')],
            ['code' => 'KY', 'name' => strToupper('Cayman Islands')],
            ['code' => 'CF', 'name' => strToupper('Central African Republic')],
            ['code' => 'TD', 'name' => strToupper('Chad')],
            ['code' => 'CL', 'name' => strToupper('Chile')],
            ['code' => 'CN', 'name' => strToupper('China')],
            ['code' => 'CX', 'name' => strToupper('Christmas Island')],
            ['code' => 'CC', 'name' => strToupper('Cocos (keeling) Islands')],
            ['code' => 'CO', 'name' => strToupper('Colombia')],
            ['code' => 'KM', 'name' => strToupper('Comoros')],
            ['code' => 'CG', 'name' => strToupper('Congo')],
            ['code' => 'CD', 'name' => strToupper('Congo, The Democratic Republic Of The')],
            ['code' => 'CK', 'name' => strToupper('Cook Islands')],
            ['code' => 'CR', 'name' => strToupper('Costa Rica')],
            ['code' => 'CI', 'name' => strToupper("Cote D'ivoire")],
            ['code' => 'HR', 'name' => strToupper('Croatia')],
            ['code' => 'CU', 'name' => strToupper('Cuba')],
            ['code' => 'CY', 'name' => strToupper('Cyprus')],
            ['code' => 'CZ', 'name' => strToupper('Czech Republic')],
            ['code' => 'DK', 'name' => strToupper('Denmark')],
            ['code' => 'DJ', 'name' => strToupper('Djibouti')],
            ['code' => 'DM', 'name' => strToupper('Dominica')],
            ['code' => 'DO', 'name' => strToupper('Dominican Republic')],
            ['code' => 'TP', 'name' => strToupper('East Timor')],
            ['code' => 'EC', 'name' => strToupper('Ecuador')],
            ['code' => 'EG', 'name' => strToupper('Egypt')],
            ['code' => 'SV', 'name' => strToupper('El Salvador')],
            ['code' => 'GQ', 'name' => strToupper('Equatorial Guinea')],
            ['code' => 'ER', 'name' => strToupper('Eritrea')],
            ['code' => 'EE', 'name' => strToupper('Estonia')],
            ['code' => 'ET', 'name' => strToupper('Ethiopia')],
            ['code' => 'FK', 'name' => strToupper('Falkland Islands (malvinas)')],
            ['code' => 'FO', 'name' => strToupper('Faroe Islands')],
            ['code' => 'FJ', 'name' => strToupper('Fiji')],
            ['code' => 'FI', 'name' => strToupper('Finland')],
            ['code' => 'FR', 'name' => strToupper('France')],
            ['code' => 'GF', 'name' => strToupper('French Guiana')],
            ['code' => 'PF', 'name' => strToupper('French Polynesia')],
            ['code' => 'TF', 'name' => strToupper('French Southern Territories')],
            ['code' => 'GA', 'name' => strToupper('Gabon')],
            ['code' => 'GM', 'name' => strToupper('Gambia')],
            ['code' => 'GE', 'name' => strToupper('Georgia')],
            ['code' => 'DE', 'name' => strToupper('Germany')],
            ['code' => 'GH', 'name' => strToupper('Ghana')],
            ['code' => 'GI', 'name' => strToupper('Gibraltar')],
            ['code' => 'GR', 'name' => strToupper('Greece')],
            ['code' => 'GL', 'name' => strToupper('Greenland')],
            ['code' => 'GD', 'name' => strToupper('Grenada')],
            ['code' => 'GP', 'name' => strToupper('Guadeloupe')],
            ['code' => 'GU', 'name' => strToupper('Guam')],
            ['code' => 'GT', 'name' => strToupper('Guatemala')],
            ['code' => 'GN', 'name' => strToupper('Guinea')],
            ['code' => 'GW', 'name' => strToupper('Guinea-bissau')],
            ['code' => 'GY', 'name' => strToupper('Guyana')],
            ['code' => 'HT', 'name' => strToupper('Haiti')],
            ['code' => 'HM', 'name' => strToupper('Heard Island And Mcdonald Islands')],
            ['code' => 'VA', 'name' => strToupper('Holy See (vatican City State)')],
            ['code' => 'HN', 'name' => strToupper('Honduras')],
            ['code' => 'HK', 'name' => strToupper('Hong Kong')],
            ['code' => 'HU', 'name' => strToupper('Hungary')],
            ['code' => 'IS', 'name' => strToupper('Iceland')],
            ['code' => 'IN', 'name' => strToupper('India')],
            ['code' => 'ID', 'name' => strToupper('Indonesia')],
            ['code' => 'IR', 'name' => strToupper('Iran, Islamic Republic Of')],
            ['code' => 'IQ', 'name' => strToupper('Iraq')],
            ['code' => 'IE', 'name' => strToupper('Ireland')],
            ['code' => 'IL', 'name' => strToupper('Israel')],
            ['code' => 'IT', 'name' => strToupper('Italy')],
            ['code' => 'JM', 'name' => strToupper('Jamaica')],
            ['code' => 'JP', 'name' => strToupper('Japan')],
            ['code' => 'JO', 'name' => strToupper('Jordan')],
            ['code' => 'KZ', 'name' => strToupper('Kazakstan')],
            ['code' => 'KE', 'name' => strToupper('Kenya')],
            ['code' => 'KI', 'name' => strToupper('Kiribati')],
            ['code' => 'KP', 'name' => strToupper("Korea, Democratic People's Republic Of")],
            ['code' => 'KR', 'name' => strToupper('Korea, Republic Of')],
            ['code' => 'KV', 'name' => strToupper('Kosovo')],
            ['code' => 'KW', 'name' => strToupper('Kuwait')],
            ['code' => 'KG', 'name' => strToupper('Kyrgyzstan')],
            ['code' => 'LA', 'name' => strToupper("Lao People's Democratic Republic")],
            ['code' => 'LV', 'name' => strToupper('Latvia')],
            ['code' => 'LB', 'name' => strToupper('Lebanon')],
            ['code' => 'LS', 'name' => strToupper('Lesotho')],
            ['code' => 'LR', 'name' => strToupper('Liberia')],
            ['code' => 'LY', 'name' => strToupper('Libyan Arab Jamahiriya')],
            ['code' => 'LI', 'name' => strToupper('Liechtenstein')],
            ['code' => 'LT', 'name' => strToupper('Lithuania')],
            ['code' => 'LU', 'name' => strToupper('Luxembourg')],
            ['code' => 'MO', 'name' => strToupper('Macau')],
            ['code' => 'MK', 'name' => strToupper('Macedonia, The Former Yugoslav Republic Of')],
            ['code' => 'MG', 'name' => strToupper('Madagascar')],
            ['code' => 'MW', 'name' => strToupper('Malawi')],
            ['code' => 'MY', 'name' => strToupper('Malaysia')],
            ['code' => 'MV', 'name' => strToupper('Maldives')],
            ['code' => 'ML', 'name' => strToupper('Mali')],
            ['code' => 'MT', 'name' => strToupper('Malta')],
            ['code' => 'MH', 'name' => strToupper('Marshall Islands')],
            ['code' => 'MQ', 'name' => strToupper('Martinique')],
            ['code' => 'MR', 'name' => strToupper('Mauritania')],
            ['code' => 'MU', 'name' => strToupper('Mauritius')],
            ['code' => 'YT', 'name' => strToupper('Mayotte')],
            ['code' => 'MX', 'name' => strToupper('Mexico')],
            ['code' => 'FM', 'name' => strToupper('Micronesia, Federated States Of')],
            ['code' => 'MD', 'name' => strToupper('Moldova, Republic Of')],
            ['code' => 'MC', 'name' => strToupper('Monaco')],
            ['code' => 'MN', 'name' => strToupper('Mongolia')],
            ['code' => 'MS', 'name' => strToupper('Montserrat')],
            ['code' => 'ME', 'name' => strToupper('Montenegro')],
            ['code' => 'MA', 'name' => strToupper('Morocco')],
            ['code' => 'MZ', 'name' => strToupper('Mozambique')],
            ['code' => 'MM', 'name' => strToupper('Myanmar')],
            ['code' => 'NA', 'name' => strToupper('Namibia')],
            ['code' => 'NR', 'name' => strToupper('Nauru')],
            ['code' => 'NP', 'name' => strToupper('Nepal')],
            ['code' => 'NL', 'name' => strToupper('Netherlands')],
            ['code' => 'AN', 'name' => strToupper('Netherlands Antilles')],
            ['code' => 'NC', 'name' => strToupper('New Caledonia')],
            ['code' => 'NZ', 'name' => strToupper('New Zealand')],
            ['code' => 'NI', 'name' => strToupper('Nicaragua')],
            ['code' => 'NE', 'name' => strToupper('Niger')],
            ['code' => 'NG', 'name' => strToupper('Nigeria')],
            ['code' => 'NU', 'name' => strToupper('Niue')],
            ['code' => 'NF', 'name' => strToupper('Norfolk Island')],
            ['code' => 'MP', 'name' => strToupper('Northern Mariana Islands')],
            ['code' => 'NO', 'name' => strToupper('Norway')],
            ['code' => 'OM', 'name' => strToupper('Oman')],
            ['code' => 'PK', 'name' => strToupper('Pakistan')],
            ['code' => 'PW', 'name' => strToupper('Palau')],
            ['code' => 'PS', 'name' => strToupper('Palestinian Territory, Occupied')],
            ['code' => 'PA', 'name' => strToupper('Panama')],
            ['code' => 'PG', 'name' => strToupper('Papua New Guinea')],
            ['code' => 'PY', 'name' => strToupper('Paraguay')],
            ['code' => 'PE', 'name' => strToupper('Peru')],
            ['code' => 'PH', 'name' => strToupper('Philippines')],
            ['code' => 'PN', 'name' => strToupper('Pitcairn')],
            ['code' => 'PL', 'name' => strToupper('Poland')],
            ['code' => 'PT', 'name' => strToupper('Portugal')],
            ['code' => 'PR', 'name' => strToupper('Puerto Rico')],
            ['code' => 'QA', 'name' => strToupper('Qatar')],
            ['code' => 'RE', 'name' => strToupper('Reunion')],
            ['code' => 'RO', 'name' => strToupper('Romania')],
            ['code' => 'RU', 'name' => strToupper('Russian Federation')],
            ['code' => 'RW', 'name' => strToupper('Rwanda')],
            ['code' => 'SH', 'name' => strToupper('Saint Helena')],
            ['code' => 'KN', 'name' => strToupper('Saint Kitts And Nevis')],
            ['code' => 'LC', 'name' => strToupper('Saint Lucia')],
            ['code' => 'PM', 'name' => strToupper('Saint Pierre And Miquelon')],
            ['code' => 'VC', 'name' => strToupper('Saint Vincent And The Grenadines')],
            ['code' => 'WS', 'name' => strToupper('Samoa')],
            ['code' => 'SM', 'name' => strToupper('San Marino')],
            ['code' => 'ST', 'name' => strToupper('Sao Tome And Principe')],
            ['code' => 'SA', 'name' => strToupper('Saudi Arabia')],
            ['code' => 'SN', 'name' => strToupper('Senegal')],
            ['code' => 'RS', 'name' => strToupper('Serbia')],
            ['code' => 'SC', 'name' => strToupper('Seychelles')],
            ['code' => 'SL', 'name' => strToupper('Sierra Leone')],
            ['code' => 'SG', 'name' => strToupper('Singapore')],
            ['code' => 'SK', 'name' => strToupper('Slovakia')],
            ['code' => 'SI', 'name' => strToupper('Slovenia')],
            ['code' => 'SB', 'name' => strToupper('Solomon Islands')],
            ['code' => 'SO', 'name' => strToupper('Somalia')],
            ['code' => 'ZA', 'name' => strToupper('South Africa')],
            ['code' => 'GS', 'name' => strToupper('South Georgia And The South Sandwich Islands')],
            ['code' => 'ES', 'name' => strToupper('Spain')],
            ['code' => 'LK', 'name' => strToupper('Sri Lanka')],
            ['code' => 'SD', 'name' => strToupper('Sudan')],
            ['code' => 'SR', 'name' => strToupper('Suriname')],
            ['code' => 'SJ', 'name' => strToupper('Svalbard And Jan Mayen')],
            ['code' => 'SZ', 'name' => strToupper('Swaziland')],
            ['code' => 'SE', 'name' => strToupper('Sweden')],
            ['code' => 'CH', 'name' => strToupper('Switzerland')],
            ['code' => 'SY', 'name' => strToupper('Syrian Arab Republic')],
            ['code' => 'TW', 'name' => strToupper('Taiwan, Province Of China')],
            ['code' => 'TJ', 'name' => strToupper('Tajikistan')],
            ['code' => 'TZ', 'name' => strToupper('Tanzania, United Republic Of')],
            ['code' => 'TH', 'name' => strToupper('Thailand')],
            ['code' => 'TG', 'name' => strToupper('Togo')],
            ['code' => 'TK', 'name' => strToupper('Tokelau')],
            ['code' => 'TO', 'name' => strToupper('Tonga')],
            ['code' => 'TT', 'name' => strToupper('Trinidad And Tobago')],
            ['code' => 'TN', 'name' => strToupper('Tunisia')],
            ['code' => 'TR', 'name' => strToupper('Turkey')],
            ['code' => 'TM', 'name' => strToupper('Turkmenistan')],
            ['code' => 'TC', 'name' => strToupper('Turks And Caicos Islands')],
            ['code' => 'TV', 'name' => strToupper('Tuvalu')],
            ['code' => 'UG', 'name' => strToupper('Uganda')],
            ['code' => 'UA', 'name' => strToupper('Ukraine')],
            ['code' => 'AE', 'name' => strToupper('United Arab Emirates')],
            ['code' => 'GB', 'name' => strToupper('United Kingdom')],
            ['code' => 'US', 'name' => strToupper('United States')],
            ['code' => 'UM', 'name' => strToupper('United States Minor Outlying Islands')],
            ['code' => 'UY', 'name' => strToupper('Uruguay')],
            ['code' => 'UZ', 'name' => strToupper('Uzbekistan')],
            ['code' => 'VU', 'name' => strToupper('Vanuatu')],
            ['code' => 'VE', 'name' => strToupper('Venezuela')],
            ['code' => 'VN', 'name' => strToupper('Viet Nam')],
            ['code' => 'VG', 'name' => strToupper('Virgin Islands, British')],
            ['code' => 'VI', 'name' => strToupper('Virgin Islands, U.s.')],
            ['code' => 'WF', 'name' => strToupper('Wallis And Futuna')],
            ['code' => 'EH', 'name' => strToupper('Western Sahara')],
            ['code' => 'YE', 'name' => strToupper('Yemen')],
            ['code' => 'ZM', 'name' => strToupper('Zambia')],
            ['code' => 'ZW', 'name' => strToupper('Zimbabwe')],
        ]);
    }
}
