<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CurrenciesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('currencies')->insert([
            ['code' => 'AED', 'name' => strToUpper('United Arab Emirates Dirham')],
            ['code' => 'AFN', 'name' => strToUpper('Afghan Afghani')],
            ['code' => 'ALL', 'name' => strToUpper('Albanian Lek')],
            ['code' => 'AMD', 'name' => strToUpper('Armenian Dram')],
            ['code' => 'ANG', 'name' => strToUpper('Netherlands Antillean Guilder')],
            ['code' => 'AOA', 'name' => strToUpper('Angolan Kwanza')],
            ['code' => 'ARS', 'name' => strToUpper('Argentine Peso')],
            ['code' => 'AUD', 'name' => strToUpper('Australian Dollar')],
            ['code' => 'AWG', 'name' => strToUpper('Aruban Florin')],
            ['code' => 'AZN', 'name' => strToUpper('Azerbaijani Manat')],
            ['code' => 'BAM', 'name' => strToUpper('Bosnia-Herzegovina Convertible Mark')],
            ['code' => 'BBD', 'name' => strToUpper('Barbadian Dollar')],
            ['code' => 'BDT', 'name' => strToUpper('Bangladeshi Taka')],
            ['code' => 'BGN', 'name' => strToUpper('Bulgarian Lev')],
            ['code' => 'BHD', 'name' => strToUpper('Bahraini Dinar')],
            ['code' => 'BIF', 'name' => strToUpper('Burundian Franc')],
            ['code' => 'BMD', 'name' => strToUpper('Bermudan Dollar')],
            ['code' => 'BND', 'name' => strToUpper('Brunei Dollar')],
            ['code' => 'BOB', 'name' => strToUpper('Bolivian Boliviano')],
            ['code' => 'BRL', 'name' => strToUpper('Brazilian Real')],
            ['code' => 'BSD', 'name' => strToUpper('Bahamian Dollar')],
            ['code' => 'BTC', 'name' => strToUpper('Bitcoin')],
            ['code' => 'BTN', 'name' => strToUpper('Bhutanese Ngultrum')],
            ['code' => 'BWP', 'name' => strToUpper('Botswanan Pula')],
            ['code' => 'BYN', 'name' => strToUpper('Belarusian Ruble')],
            ['code' => 'BZD', 'name' => strToUpper('Belize Dollar')],
            ['code' => 'CAD', 'name' => strToUpper('Canadian Dollar')],
            ['code' => 'CDF', 'name' => strToUpper('Congolese Franc')],
            ['code' => 'CHF', 'name' => strToUpper('Swiss Franc')],
            ['code' => 'CLF', 'name' => strToUpper('Chilean Unit of Account (UF)')],
            ['code' => 'CLP', 'name' => strToUpper('Chilean Peso')],
            ['code' => 'CNH', 'name' => strToUpper('Chinese Yuan (Offshore)')],
            ['code' => 'CNY', 'name' => strToUpper('Chinese Yuan')],
            ['code' => 'COP', 'name' => strToUpper('Colombian Peso')],
            ['code' => 'CRC', 'name' => strToUpper('Costa Rican Colón')],
            ['code' => 'CUC', 'name' => strToUpper('Cuban Convertible Peso')],
            ['code' => 'CUP', 'name' => strToUpper('Cuban Peso')],
            ['code' => 'CVE', 'name' => strToUpper('Cape Verdean Escudo')],
            ['code' => 'CZK', 'name' => strToUpper('Czech Republic Koruna')],
            ['code' => 'DJF', 'name' => strToUpper('Djiboutian Franc')],
            ['code' => 'DKK', 'name' => strToUpper('Danish Krone')],
            ['code' => 'DOP', 'name' => strToUpper('Dominican Peso')],
            ['code' => 'DZD', 'name' => strToUpper('Algerian Dinar')],
            ['code' => 'EGP', 'name' => strToUpper('Egyptian Pound')],
            ['code' => 'ERN', 'name' => strToUpper('Eritrean Nakfa')],
            ['code' => 'ETB', 'name' => strToUpper('Ethiopian Birr')],
            ['code' => 'EUR', 'name' => strToUpper('Euro')],
            ['code' => 'FJD', 'name' => strToUpper('Fijian Dollar')],
            ['code' => 'FKP', 'name' => strToUpper('Falkland Islands Pound')],
            ['code' => 'GBP', 'name' => strToUpper('British Pound Sterling')],
            ['code' => 'GEL', 'name' => strToUpper('Georgian Lari')],
            ['code' => 'GGP', 'name' => strToUpper('Guernsey Pound')],
            ['code' => 'GHS', 'name' => strToUpper('Ghanaian Cedi')],
            ['code' => 'GIP', 'name' => strToUpper('Gibraltar Pound')],
            ['code' => 'GMD', 'name' => strToUpper('Gambian Dalasi')],
            ['code' => 'GNF', 'name' => strToUpper('Guinean Franc')],
            ['code' => 'GTQ', 'name' => strToUpper('Guatemalan Quetzal')],
            ['code' => 'GYD', 'name' => strToUpper('Guyanaese Dollar')],
            ['code' => 'HKD', 'name' => strToUpper('Hong Kong Dollar')],
            ['code' => 'HNL', 'name' => strToUpper('Honduran Lempira')],
            ['code' => 'HRK', 'name' => strToUpper('Croatian Kuna')],
            ['code' => 'HTG', 'name' => strToUpper('Haitian Gourde')],
            ['code' => 'HUF', 'name' => strToUpper('Hungarian Forint')],
            ['code' => 'IDR', 'name' => strToUpper('Indonesian Rupiah')],
            ['code' => 'ILS', 'name' => strToUpper('Israeli New Sheqel')],
            ['code' => 'IMP', 'name' => strToUpper('Manx pound')],
            ['code' => 'INR', 'name' => strToUpper('Indian Rupee')],
            ['code' => 'IQD', 'name' => strToUpper('Iraqi Dinar')],
            ['code' => 'IRR', 'name' => strToUpper('Iranian Rial')],
            ['code' => 'ISK', 'name' => strToUpper('Icelandic Króna')],
            ['code' => 'JEP', 'name' => strToUpper('Jersey Pound')],
            ['code' => 'JMD', 'name' => strToUpper('Jamaican Dollar')],
            ['code' => 'JOD', 'name' => strToUpper('Jordanian Dinar')],
            ['code' => 'JPY', 'name' => strToUpper('Japanese Yen')],
            ['code' => 'KES', 'name' => strToUpper('Kenyan Shilling')],
            ['code' => 'KGS', 'name' => strToUpper('Kyrgystani Som')],
            ['code' => 'KHR', 'name' => strToUpper('Cambodian Riel')],
            ['code' => 'KMF', 'name' => strToUpper('Comorian Franc')],
            ['code' => 'KPW', 'name' => strToUpper('North Korean Won')],
            ['code' => 'KRW', 'name' => strToUpper('South Korean Won')],
            ['code' => 'KWD', 'name' => strToUpper('Kuwaiti Dinar')],
            ['code' => 'KYD', 'name' => strToUpper('Cayman Islands Dollar')],
            ['code' => 'KZT', 'name' => strToUpper('Kazakhstani Tenge')],
            ['code' => 'LAK', 'name' => strToUpper('Laotian Kip')],
            ['code' => 'LBP', 'name' => strToUpper('Lebanese Pound')],
            ['code' => 'LKR', 'name' => strToUpper('Sri Lankan Rupee')],
            ['code' => 'LRD', 'name' => strToUpper('Liberian Dollar')],
            ['code' => 'LSL', 'name' => strToUpper('Lesotho Loti')],
            ['code' => 'LYD', 'name' => strToUpper('Libyan Dinar')],
            ['code' => 'MAD', 'name' => strToUpper('Moroccan Dirham')],
            ['code' => 'MDL', 'name' => strToUpper('Moldovan Leu')],
            ['code' => 'MGA', 'name' => strToUpper('Malagasy Ariary')],
            ['code' => 'MKD', 'name' => strToUpper('Macedonian Denar')],
            ['code' => 'MMK', 'name' => strToUpper('Myanma Kyat')],
            ['code' => 'MNT', 'name' => strToUpper('Mongolian Tugrik')],
            ['code' => 'MOP', 'name' => strToUpper('Macanese Pataca')],
            ['code' => 'MRO', 'name' => strToUpper('Mauritanian Ouguiya (pre-2018)')],
            ['code' => 'MRU', 'name' => strToUpper('Mauritanian Ouguiya')],
            ['code' => 'MUR', 'name' => strToUpper('Mauritian Rupee')],
            ['code' => 'MVR', 'name' => strToUpper('Maldivian Rufiyaa')],
            ['code' => 'MWK', 'name' => strToUpper('Malawian Kwacha')],
            ['code' => 'MXN', 'name' => strToUpper('Mexican Peso')],
            ['code' => 'MYR', 'name' => strToUpper('Malaysian Ringgit')],
            ['code' => 'MZN', 'name' => strToUpper('Mozambican Metical')],
            ['code' => 'NAD', 'name' => strToUpper('Namibian Dollar')],
            ['code' => 'NGN', 'name' => strToUpper('Nigerian Naira')],
            ['code' => 'NIO', 'name' => strToUpper('Nicaraguan Córdoba')],
            ['code' => 'NOK', 'name' => strToUpper('Norwegian Krone')],
            ['code' => 'NPR', 'name' => strToUpper('Nepalese Rupee')],
            ['code' => 'NZD', 'name' => strToUpper('New Zealand Dollar')],
            ['code' => 'OMR', 'name' => strToUpper('Omani Rial')],
            ['code' => 'PAB', 'name' => strToUpper('Panamanian Balboa')],
            ['code' => 'PEN', 'name' => strToUpper('Peruvian Nuevo Sol')],
            ['code' => 'PGK', 'name' => strToUpper('Papua New Guinean Kina')],
            ['code' => 'PHP', 'name' => strToUpper('Philippine Peso')],
            ['code' => 'PKR', 'name' => strToUpper('Pakistani Rupee')],
            ['code' => 'PLN', 'name' => strToUpper('Polish Zloty')],
            ['code' => 'PYG', 'name' => strToUpper('Paraguayan Guarani')],
            ['code' => 'QAR', 'name' => strToUpper('Qatari Rial')],
            ['code' => 'RON', 'name' => strToUpper('Romanian Leu')],
            ['code' => 'RSD', 'name' => strToUpper('Serbian Dinar')],
            ['code' => 'RUB', 'name' => strToUpper('Russian Ruble')],
            ['code' => 'RWF', 'name' => strToUpper('Rwandan Franc')],
            ['code' => 'SAR', 'name' => strToUpper('Saudi Riyal')],
            ['code' => 'SBD', 'name' => strToUpper('Solomon Islands Dollar')],
            ['code' => 'SCR', 'name' => strToUpper('Seychellois Rupee')],
            ['code' => 'SDG', 'name' => strToUpper('Sudanese Pound')],
            ['code' => 'SEK', 'name' => strToUpper('Swedish Krona')],
            ['code' => 'SGD', 'name' => strToUpper('Singapore Dollar')],
            ['code' => 'SHP', 'name' => strToUpper('Saint Helena Pound')],
            ['code' => 'SLL', 'name' => strToUpper('Sierra Leonean Leone')],
            ['code' => 'SOS', 'name' => strToUpper('Somali Shilling')],
            ['code' => 'SRD', 'name' => strToUpper('Surinamese Dollar')],
            ['code' => 'SSP', 'name' => strToUpper('South Sudanese Pound')],
            ['code' => 'STD', 'name' => strToUpper('São Tomé and Príncipe Dobra (pre-2018)')],
            ['code' => 'STN', 'name' => strToUpper('São Tomé and Príncipe Dobra')],
            ['code' => 'SVC', 'name' => strToUpper('Salvadoran Colón')],
            ['code' => 'SYP', 'name' => strToUpper('Syrian Pound')],
            ['code' => 'SZL', 'name' => strToUpper('Swazi Lilangeni')],
            ['code' => 'THB', 'name' => strToUpper('Thai Baht')],
            ['code' => 'TJS', 'name' => strToUpper('Tajikistani Somoni')],
            ['code' => 'TMT', 'name' => strToUpper('Turkmenistani Manat')],
            ['code' => 'TND', 'name' => strToUpper('Tunisian Dinar')],
            ['code' => 'TOP', 'name' => strToUpper("Tongan Pa'anga")],
            ['code' => 'TRY', 'name' => strToUpper('Turkish Lira')],
            ['code' => 'TTD', 'name' => strToUpper('Trinidad and Tobago Dollar')],
            ['code' => 'TWD', 'name' => strToUpper('New Taiwan Dollar')],
            ['code' => 'TZS', 'name' => strToUpper('Tanzanian Shilling')],
            ['code' => 'UAH', 'name' => strToUpper('Ukrainian Hryvnia')],
            ['code' => 'UGX', 'name' => strToUpper('Ugandan Shilling')],
            ['code' => 'USD', 'name' => strToUpper('United States Dollar')],
            ['code' => 'UYU', 'name' => strToUpper('Uruguayan Peso')],
            ['code' => 'UZS', 'name' => strToUpper('Uzbekistan Som')],
            ['code' => 'VEF', 'name' => strToUpper('Venezuelan Bolívar Fuerte')],
            ['code' => 'VND', 'name' => strToUpper('Vietnamese Dong')],
            ['code' => 'VUV', 'name' => strToUpper('Vanuatu Vatu')],
            ['code' => 'WST', 'name' => strToUpper('Samoan Tala')],
            ['code' => 'XAF', 'name' => strToUpper('CFA Franc BEAC')],
            ['code' => 'XAG', 'name' => strToUpper('Silver Ounce')],
            ['code' => 'XAU', 'name' => strToUpper('Gold Ounce')],
            ['code' => 'XCD', 'name' => strToUpper('East Caribbean Dollar')],
            ['code' => 'XDR', 'name' => strToUpper('Special Drawing Rights')],
            ['code' => 'XOF', 'name' => strToUpper('CFA Franc BCEAO')],
            ['code' => 'XPD', 'name' => strToUpper('Palladium Ounce')],
            ['code' => 'XPF', 'name' => strToUpper('CFP Franc')],
            ['code' => 'XPT', 'name' => strToUpper('Platinum Ounce')],
            ['code' => 'YER', 'name' => strToUpper('Yemeni Rial')],
            ['code' => 'ZAR', 'name' => strToUpper('South African Rand')],
            ['code' => 'ZMW', 'name' => strToUpper('Zambian Kwacha')],
            ['code' => 'ZWL', 'name' => strToUpper('Zimbabwean Dollar')]
        ]);
    }
}
