<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NeighborhoodsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $id = DB::table('zones')->insert([
            ['name' => 'RIOMAR', 'city_id' => 126],
        ]);

        DB::table('neighborhoods')->insert([
            ['name' => strToUpper('La Playa'), 'zone_id' => $id],
            ['name' => strToUpper('Villa Santos'), 'zone_id' => $id],
            ['name' => strToUpper('Urbanizacion La Playa'), 'zone_id' => $id],
            ['name' => strToUpper('Villa campestre'), 'zone_id' => $id],
            ['name' => strToUpper('El Poblado'), 'zone_id' => $id],
            ['name' => strToUpper('Altamira'), 'zone_id' => $id],
            ['name' => strToUpper('San Vicente'), 'zone_id' => $id],
            ['name' => strToUpper('Altos del Limon'), 'zone_id' => $id],
            ['name' => strToUpper('Altos de Riomar'), 'zone_id' => $id],
            ['name' => strToUpper('Santa Monica'), 'zone_id' => $id],
            ['name' => strToUpper('Riomar'), 'zone_id' => $id],
            ['name' => strToUpper('Andalucia'), 'zone_id' => $id],
            ['name' => strToUpper('Las Flores'), 'zone_id' => $id],
            ['name' => strToUpper('La Floresta'), 'zone_id' => $id],
            ['name' => strToUpper('San Salvador'), 'zone_id' => $id],
            ['name' => strToUpper('Siape'), 'zone_id' => $id],
            ['name' => strToUpper('Las Tres Avemarias'), 'zone_id' => $id],
            ['name' => strToUpper('Villa del Este'), 'zone_id' => $id],
            ['name' => strToUpper('El Castillo'), 'zone_id' => $id],
            ['name' => strToUpper('Solaire'), 'zone_id' => $id],
            ['name' => strToUpper('Paraiso'), 'zone_id' => $id],
            ['name' => strToUpper('El Limoncito'), 'zone_id' => $id],
            ['name' => strToUpper('Altos del Prado'), 'zone_id' => $id],
            ['name' => strToUpper('La Castellana'), 'zone_id' => $id],
            ['name' => strToUpper('Villa Carolina'), 'zone_id' => $id],
            ['name' => strToUpper('El Golf'), 'zone_id' => $id],
            ['name' => strToUpper('San Marino'), 'zone_id' => $id],
            ['name' => strToUpper('Adela de Char'), 'zone_id' => $id],
        ]);
    
        $id = DB::table('zones')->insert([
            ['name' => 'NORTE-CENTRO HISTORICO', 'city_id' => 126],
        ]);
        DB::table('neighborhoods')->insert([
            ['name' => strToUpper('Modelo'), 'zone_id' => $id],
            ['name' => strToUpper('Alameda del Rio'), 'zone_id' => $id],
            ['name' => strToUpper('Ciudad Jardin'), 'zone_id' => $id],
            ['name' => strToUpper('La Campiña'), 'zone_id' => $id],
            ['name' => strToUpper('El Tabor'), 'zone_id' => $id],
            ['name' => strToUpper('Miramar'), 'zone_id' => $id],
            ['name' => strToUpper('Granadillo'), 'zone_id' => $id],
            ['name' => strToUpper('Los Alpes'), 'zone_id' => $id],
            ['name' => strToUpper('Nuevo Horizonte'), 'zone_id' => $id],
            ['name' => strToUpper('El Porvenir'), 'zone_id' => $id],
            ['name' => strToUpper('Altos del Prado'), 'zone_id' => $id],
            ['name' => strToUpper('El Golf'), 'zone_id' => $id],
            ['name' => strToUpper('El Country'), 'zone_id' => $id],
            ['name' => strToUpper('Paraiso'), 'zone_id' => $id],
            ['name' => strToUpper('Los Nogales'), 'zone_id' => $id],
            ['name' => strToUpper('La Concepcion'), 'zone_id' => $id],
            ['name' => strToUpper('San Francisco'), 'zone_id' => $id],
            ['name' => strToUpper('Santa Ana'), 'zone_id' => $id],
            ['name' => strToUpper('America'), 'zone_id' => $id],
            ['name' => strToUpper('Colombia'), 'zone_id' => $id],
            ['name' => strToUpper('El Prado'), 'zone_id' => $id],
            ['name' => strToUpper('Bellavista'), 'zone_id' => $id],
            ['name' => strToUpper('Montecristo'), 'zone_id' => $id],
            ['name' => strToUpper('Abajo'), 'zone_id' => $id],
            ['name' => strToUpper('La Felicidad'), 'zone_id' => $id],
            ['name' => strToUpper('La Cumbre'), 'zone_id' => $id],
            ['name' => strToUpper('Nuevo Horizonte'), 'zone_id' => $id],
            ['name' => strToUpper('Campo Alegre'), 'zone_id' => $id],
            ['name' => strToUpper('Las Colinas'), 'zone_id' => $id],
            ['name' => strToUpper('Los Jobos'), 'zone_id' => $id],
            ['name' => strToUpper('Las Mercedes'), 'zone_id' => $id],
            ['name' => strToUpper('Betania'), 'zone_id' => $id],
            ['name' => strToUpper('Las Delicias'), 'zone_id' => $id],
            ['name' => strToUpper('El Recreo'), 'zone_id' => $id],
            ['name' => strToUpper('Boston'), 'zone_id' => $id],
            ['name' => strToUpper('El Rosario'), 'zone_id' => $id],
            ['name' => strToUpper('Centro'), 'zone_id' => $id],
            ['name' => strToUpper('Barlovento'), 'zone_id' => $id],
            ['name' => strToUpper('Villanueva'), 'zone_id' => $id],
            ['name' => strToUpper('El Boliche'), 'zone_id' => $id],
        ]);

        $id = DB::table('zones')->insert([
            ['name' => 'METROPOLITANA', 'city_id' => 126],
        ]);
        DB::table('neighborhoods')->insert([
            ['name' => strToUpper('Buenos Aires'), 'zone_id' => $id],
            ['name' => strToUpper('Carrizal'), 'zone_id' => $id],
            ['name' => strToUpper('Siete de Abril'), 'zone_id' => $id],
            ['name' => strToUpper('Cevillar'), 'zone_id' => $id],
            ['name' => strToUpper('Ciudadela 20 de Julio'), 'zone_id' => $id],
            ['name' => strToUpper('El Santuario'), 'zone_id' => $id],
            ['name' => strToUpper('Kennedy'), 'zone_id' => $id],
            ['name' => strToUpper('La Arboraya'), 'zone_id' => $id],
            ['name' => strToUpper('La Sierra'), 'zone_id' => $id],
            ['name' => strToUpper('La Victoria'), 'zone_id' => $id],
            ['name' => strToUpper('Las Americas'), 'zone_id' => $id],
            ['name' => strToUpper('Las Gardenias'), 'zone_id' => $id],
            ['name' => strToUpper('Las Granjas'), 'zone_id' => $id],
            ['name' => strToUpper('Los Continentes'), 'zone_id' => $id],
            ['name' => strToUpper('Los Girasoles'), 'zone_id' => $id],
            ['name' => strToUpper('San Jose'), 'zone_id' => $id],
            ['name' => strToUpper('San Luis'), 'zone_id' => $id],
            ['name' => strToUpper('Santa Maria'), 'zone_id' => $id],
            ['name' => strToUpper('Urbanizacion Las Cayenas'), 'zone_id' => $id],
            ['name' => strToUpper('Veinte de Julio'), 'zone_id' => $id],
            ['name' => strToUpper('Villa San Carlos'), 'zone_id' => $id],
            ['name' => strToUpper('Villa San Pedro II'), 'zone_id' => $id],
            ['name' => strToUpper('Villa Sevilla'), 'zone_id' => $id],
        ]);

        $id = DB::table('zones')->insert([
            ['name' => 'SUR-OCCIDENTE', 'city_id' => 126],
        ]);
        DB::table('neighborhoods')->insert([
            ['name' => strToUpper('Alfonso Lopez'), 'zone_id' => $id],
            ['name' => strToUpper('Bernando Hoyos'), 'zone_id' => $id],
            ['name' => strToUpper('Buena Esperanza'), 'zone_id' => $id],
            ['name' => strToUpper('California'), 'zone_id' => $id],
            ['name' => strToUpper('Caribe Verde'), 'zone_id' => $id],
            ['name' => strToUpper('Carlos Meisel'), 'zone_id' => $id],
            ['name' => strToUpper('Cevillar'), 'zone_id' => $id],
            ['name' => strToUpper('Chiquinquira'), 'zone_id' => $id],
            ['name' => strToUpper('Ciudad Modesto'), 'zone_id' => $id],
            ['name' => strToUpper('Ciudadela de La Salud'), 'zone_id' => $id],
            ['name' => strToUpper('Ciudadela de La Paz'), 'zone_id' => $id],
            ['name' => strToUpper('Colina Campestre'), 'zone_id' => $id],
            ['name' => strToUpper('Conjunto Residencial Prados Del Eden'), 'zone_id' => $id],
            ['name' => strToUpper('Cordialidad'), 'zone_id' => $id],
            ['name' => strToUpper('Corrigimiento Juan Mina'), 'zone_id' => $id],
            ['name' => strToUpper('Cuchilla de Villate'), 'zone_id' => $id],
            ['name' => strToUpper('El Bosque'), 'zone_id' => $id],
            ['name' => strToUpper('El Carmen'), 'zone_id' => $id],
            ['name' => strToUpper('El Eden'), 'zone_id' => $id],
            ['name' => strToUpper('El Golfo'), 'zone_id' => $id],
            ['name' => strToUpper('El Pueblo'), 'zone_id' => $id],
            ['name' => strToUpper('El Recreo'), 'zone_id' => $id],
            ['name' => strToUpper('El Romance'), 'zone_id' => $id],
            ['name' => strToUpper('El Rubi'), 'zone_id' => $id],
            ['name' => strToUpper('El Silencio'), 'zone_id' => $id],
            ['name' => strToUpper('El Valle'), 'zone_id' => $id],
            ['name' => strToUpper('Evaristo Sourdis'), 'zone_id' => $id],
            ['name' => strToUpper('Gerlein y Villate'), 'zone_id' => $id],
            ['name' => strToUpper('Juan Mina'), 'zone_id' => $id],
            ['name' => strToUpper('Kalamary'), 'zone_id' => $id],
            ['name' => strToUpper('La Ceiba'), 'zone_id' => $id],
            ['name' => strToUpper('La Esmeralda'), 'zone_id' => $id],
            ['name' => strToUpper('La Florida'), 'zone_id' => $id],
            ['name' => strToUpper('La Gloria'), 'zone_id' => $id],
            ['name' => strToUpper('La Libertad'), 'zone_id' => $id],
            ['name' => strToUpper('La Manga'), 'zone_id' => $id],
            ['name' => strToUpper('La Paz'), 'zone_id' => $id],
            ['name' => strToUpper('La Pradera'), 'zone_id' => $id],
            ['name' => strToUpper('La Sierra'), 'zone_id' => $id],
            ['name' => strToUpper('Las Colinas'), 'zone_id' => $id],
            ['name' => strToUpper('Las Estrellas'), 'zone_id' => $id],
            ['name' => strToUpper('Las Malvinas'), 'zone_id' => $id],
            ['name' => strToUpper('Las Terrazas'), 'zone_id' => $id],
            ['name' => strToUpper('Lipaya'), 'zone_id' => $id],
            ['name' => strToUpper('Loma Fresca'), 'zone_id' => $id],
            ['name' => strToUpper('Los Andes'), 'zone_id' => $id],
            ['name' => strToUpper('Los angeles'), 'zone_id' => $id],
            ['name' => strToUpper('Los Olivos'), 'zone_id' => $id],
            ['name' => strToUpper('Los Pinos'), 'zone_id' => $id],
            ['name' => strToUpper('Los Rosales'), 'zone_id' => $id],
            ['name' => strToUpper('Lucero'), 'zone_id' => $id],
            ['name' => strToUpper('Me Quejo'), 'zone_id' => $id],
            ['name' => strToUpper('Mercedes Sur'), 'zone_id' => $id],
            ['name' => strToUpper('Nueva Colombia'), 'zone_id' => $id],
            ['name' => strToUpper('Nueva Granada'), 'zone_id' => $id],
            ['name' => strToUpper('Olaya'), 'zone_id' => $id],
            ['name' => strToUpper('Pinar del Rio'), 'zone_id' => $id],
            ['name' => strToUpper('Por Fin'), 'zone_id' => $id],
            ['name' => strToUpper('Pumarejo'), 'zone_id' => $id],
            ['name' => strToUpper('San Felipe'), 'zone_id' => $id],
            ['name' => strToUpper('San Isidro'), 'zone_id' => $id],
            ['name' => strToUpper('San Jose (suroccidente)'), 'zone_id' => $id],
            ['name' => strToUpper('Santo Domingo'), 'zone_id' => $id],
            ['name' => strToUpper('Siete de Agosto'), 'zone_id' => $id],
            ['name' => strToUpper('Terrenos Pastoral Social'), 'zone_id' => $id],
            ['name' => strToUpper('Urbanizacion Colinas Campestre Eden 2000'), 'zone_id' => $id],
            ['name' => strToUpper('Urbanizacion El Pueblo'), 'zone_id' => $id],
            ['name' => strToUpper('Urbanizacion Villas de San Pablo'), 'zone_id' => $id],
            ['name' => strToUpper('Villa Del Rosario'), 'zone_id' => $id],
            ['name' => strToUpper('Villa Flor'), 'zone_id' => $id],
            ['name' => strToUpper('Villa San Pablo'), 'zone_id' => $id],
            ['name' => strToUpper('Villa San Pedro Alejandrino'), 'zone_id' => $id],
            ['name' => strToUpper('Villa San Pedro I Etapa'), 'zone_id' => $id],
            ['name' => strToUpper('Villate'), 'zone_id' => $id],
        ]);

        $id = DB::table('zones')->insert([
            ['name' => 'SUR-ORIENTE', 'city_id' => 126],
        ]);
        DB::table('neighborhoods')->insert([
            ['name' => strToUpper('Alfonso Lopez'), 'zone_id' => $id],
            ['name' => strToUpper('Atlantico'), 'zone_id' => $id],
            ['name' => strToUpper('Bella Arenas'), 'zone_id' => $id],
            ['name' => strToUpper('Boyaca'), 'zone_id' => $id],
            ['name' => strToUpper('Buenos Aires'), 'zone_id' => $id],
            ['name' => strToUpper('Chiquinquira'), 'zone_id' => $id],
            ['name' => strToUpper('Ciudadela 20 de Julio (suroriente)'), 'zone_id' => $id],
            ['name' => strToUpper('El Campito'), 'zone_id' => $id],
            ['name' => strToUpper('El Ferri'), 'zone_id' => $id],
            ['name' => strToUpper('El Limon'), 'zone_id' => $id],
            ['name' => strToUpper('El Milagro'), 'zone_id' => $id],
            ['name' => strToUpper('Jose Antonio Galan'), 'zone_id' => $id],
            ['name' => strToUpper('La Arboraya'), 'zone_id' => $id],
            ['name' => strToUpper('La Chinita'), 'zone_id' => $id],
            ['name' => strToUpper('La Luz'), 'zone_id' => $id],
            ['name' => strToUpper('La Magdalena'), 'zone_id' => $id],
            ['name' => strToUpper('La Union'), 'zone_id' => $id],
            ['name' => strToUpper('La Victoria (suroriente)'), 'zone_id' => $id],
            ['name' => strToUpper('Las Dunas'), 'zone_id' => $id],
            ['name' => strToUpper('Las Nieves'), 'zone_id' => $id],
            ['name' => strToUpper('Las Palmas'), 'zone_id' => $id],
            ['name' => strToUpper('Los Laureles'), 'zone_id' => $id],
            ['name' => strToUpper('Los Trupillos'), 'zone_id' => $id],
            ['name' => strToUpper('Moderno'), 'zone_id' => $id],
            ['name' => strToUpper('Montes'), 'zone_id' => $id],
            ['name' => strToUpper('Pasadena'), 'zone_id' => $id],
            ['name' => strToUpper('Primero de Mayo'), 'zone_id' => $id],
            ['name' => strToUpper('Rebolo'), 'zone_id' => $id],
            ['name' => strToUpper('San Jose'), 'zone_id' => $id],
            ['name' => strToUpper('San Nicolas'), 'zone_id' => $id],
            ['name' => strToUpper('San Roque'), 'zone_id' => $id],
            ['name' => strToUpper('Santa Helena'), 'zone_id' => $id],
            ['name' => strToUpper('Simon Bolivar'), 'zone_id' => $id],
            ['name' => strToUpper('Costa hermosa'), 'zone_id' => $id],
            ['name' => strToUpper('Tayrona'), 'zone_id' => $id],
            ['name' => strToUpper('Universal I y II'), 'zone_id' => $id],
            ['name' => strToUpper('Urbanizacion La Luz'), 'zone_id' => $id],
            ['name' => strToUpper('Villa Blanca'), 'zone_id' => $id],
            ['name' => strToUpper('Villa del Carmen'), 'zone_id' => $id],
        ]);
    }
}
